#!/bin/bash
# Simon Cavey - Projet LCS
# Desactivation du mode security d'apache sur LCS
# apt-get install libapache2-modsecurity
a2dismod mod-security
rm /etc/apache2/conf.d/00_modsecurity.conf 
rm /etc/apache2/conf.d/modsecurity_crs_10_config.conf 

echo "disable mode security apache" > /tmp/disablemodesecurity.lock

at now+1minutes <<END
/etc/init.d/apache2 restart
rm -f /tmp/disablemodesecurity.lock
END

rm -rf /var/asl
rm -rf /var/asl/tmp
rm -rf /var/asl/data
rm -rf /var/asl/data/msa
rm -rf /var/asl/data/audit
rm -rf /var/asl/data/suspicious
rm -rf /etc/apache2/modsecurity.d
rm -rf /etc/asl/
rm -f /etc/asl/whitelist
rm -f /var/log/apache2/audit_log

