#! /bin/sh

set -e

# lecture d'un parametre lcs dans lcs_db.params
get_lcsdb_params() {
mysqlpass=`cat /root/.my.cnf | grep password | cut -d "'" -f 2`
PARAMS=`echo  "SELECT value FROM params WHERE name='$1'"| mysql -u root -p$mysqlpass lcs_db -N`
echo "$PARAMS"
}

configure() {
	DNS_PRIMARY=$(get_lcsdb_params dns1)
    DNS_SECONDARY=$(get_lcsdb_params dns2)
    IPADDR0=$(get_lcsdb_params iplcs)
    HOSTNAME=$(get_lcsdb_params hostname)
    DOMAIN=$(get_lcsdb_params domain)
	# dns_reconfigure.sh <DNS_PRIMARY> <DNS_SECONDARY> <IPADDR> <HOSTNAME> <DOMAIN>
    /usr/sbin/dns_reconfigure.sh $DNS_PRIMARY $DNS_SECONDARY $IPADDR0 $HOSTNAME $DOMAIN
}

case "$1" in
    possible)
	if pgrep -u mysql mysqld >/dev/null; then
	    exit 0
	else
	    exit 1
	fi
    ;;
    needed)
	exit 0
    ;;
    configure)
	configure
    ;;
    "")
	if $0 possible && $0 needed; then
	    $0 configure
	fi
    ;;
esac
