#! /bin/sh
# postrm script for LCS squirrelmail

set -e
case "$1" in
    purge|remove)
	if pgrep -u mysql mysqld >/dev/null; then
	    mysql -e "DELETE FROM lcs_db.applis WHERE name = 'squirrelmail';"
	fi
	rm -f /etc/apache2/lcs-main/60_squirrelmail.conf
	invoke-rc.d apache2 reload >/dev/null 2>&1
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

#DEBHELPER#

exit 0
