Document: lcs-caenstats
Title: Debian lcs-caenstats Manual
Author: <insert document author here>
Abstract: This manual describes what lcs-caenstats is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lcs-caenstats/lcs-caenstats.sgml.gz

Format: postscript
Files: /usr/share/doc/lcs-caenstats/lcs-caenstats.ps.gz

Format: text
Files: /usr/share/doc/lcs-caenstats/lcs-caenstats.text.gz

Format: HTML
Index: /usr/share/doc/lcs-caenstats/html/index.html
Files: /usr/share/doc/lcs-caenstats/html/*.html

  
