#!/bin/bash
#
#### Variable a positionner en fonction du plugin
NAMEPLUGIN="Wiki"
####
#
PATH2PLUGIN="/usr/share/lcs/Plugins/$NAMEPLUGIN"
echo "Script d'installation du plugin Wiki";
#
# Ajout de l'adresse mel d'admin dans la table params
#
#
# Nettoyage
#
rm $PATH2PLUGIN/Admin/install_mysql.sql
