#! /bin/sh

case "$1" in
	configure)
		if [ -e /etc/squid/fonts/Verdana.TTF ] ; then
			rm /etc/squid/fonts/Verdana.TTF
		fi

		if [ -e /etc/squid/fonts/license ] ; then
			rm /etc/squid/fonts/license
		fi

		if [ -e /etc/squid/fonts/README ] ; then
			rm /etc/squid/fonts/README
		fi

		if [ -e /etc/squid/sarg-maint.sh ] ; then
			rm /etc/squid/sarg-maint.sh
		fi
                #
                # Validate menu statistiques squid in menu 40stats.inc
                #
                if [ -e /var/www/lcs/includes/menu.d/40stats.inc ]; then
                    sed -i "s/.*Mandataire.*/\t\"Mandataire cache\",\"..\/squid-reports\/\",\"lcs_is_admin\",/" /var/www/lcs/includes/menu.d/40stats.inc
                fi
    	;;
	abort-upgrade|abort-remove|abort-deconfigure)
		#
		#     do nothing.
		#
		exit 0
	;;
	*)
		#
		#	Unknown action - do nothing.
		#
		exit 0
	;;
esac

#DEBHELPER#
