#!/bin/bash
#
#### Variable a positionner en fonction du plugin
NAMEPLUGIN="Gedowl"
####
#
PATH2PLUGIN="/usr/share/lcs/Plugins/$NAMEPLUGIN"
echo "Script d'installation du module Gedowl";
#
# Nettoyage
#
rm $PATH2PLUGIN/Admin/install_mysql.sql
mv $PATH2PLUGIN/Admin/install_mysql.sq $PATH2PLUGIN/Admin/install_mysql.sql
#
#
#

echo "# Debut section gedowl plugin" >> /etc/apache2/lcs-main/70_gedowl.conf
echo "<Directory /usr/share/lcs/Plugins/Gedowl/Documents>" >> /etc/apache2/lcs-main/70_gedowl.conf
echo "       Deny From all ">> /etc/apache2/lcs-main/70_gedowl.conf
echo "</Directory>" >> /etc/apache2/lcs-main/70_gedowl.conf
echo "# Fin section gedowl plugin" >> /etc/apache2/lcs-main/70_gedowl.conf
# Redemarrage apache2
#
echo "Apache2 sera redémarré dans une minute"
at now +1 minutes < /usr/share/lcs/Plugins/Gedowl/Admin/jobat2

