#!/bin/sh
set -e

VER=$(dpkg-query -f '${Version}' -W lcs-desktop)
MODULE="desktop"
VERAPPLI=$VER
INDICEMAJNBR="0"

if [ "$2" = "" ] || [ "$2" = "$VER" ]; then
    #
    # Inscription du module dans applis.lcs_db
    #
    /usr/bin/mysql -e "INSERT INTO lcs_db.applis (id, name, value, descr, num_maj, version, chemin, type) VALUES ('', '$MODULE', '1', 'Web desktop', '$INDICEMAJNBR', '$VER', '$PATHMOD', 'M');"
    #
    # Create Profile user
    #
    cd /home
    for rep in *; do
        if [ -n "$(ldapsearch -xLLL uid=$rep >&1 /dev/null)" ]; then
		if [ ! -d $rep/Profile ]; then
                	mkdir -p $rep/Profile
                	chown -R www-data:lcs-users $rep/Profile
                	chmod 750 /home/$rep/Profile
		fi
        fi
    done
    #
    # Reload apache
    #
    invoke-rc.d apache2 force-reload
else
    echo "Mise à jour du paquet module LCS $MODULE de $2 vers $VER"
    #
    # Lecture de l'indice de maj dans la table lcs_db.applis
    #
    MAJNBR=`mysql -se "SELECT num_maj FROM lcs_db.applis WHERE name='$MODULE';"`
    MAJNBR=$((MAJNBR+1))
    if [ ! -e $CONF/Maj/maj$MAJNBR.sh ]; then
	echo "Pas de script de mise à jour à appliquer !"
    else
        while [ -e $CONF/Maj/maj$MAJNBR.sh ]; do
            echo "Application du script Maj$MAJNBR"
            $CONF/Maj/maj$MAJNBR.sh
             MAJNBR=$((MAJNBR+1))
	done
        #
        # Fin de la mise à jour
        #
        echo "Application des maj terminée."
    fi
    #
    # Mise à jour de l'indice de Maj
    #
    /usr/bin/mysql -e "UPDATE lcs_db.applis SET num_maj='$INDICEMAJNBR', version='$VER' WHERE name='$MODULE';"
fi
#
# Actions non liées a une installation initiale ou à une mise à jour.
#
#
# Mise en place du lien symbolique pour la doc
#
if [ ! -e /usr/share/doc/lcs-$MODULE ]; then
    ln -s /usr/share/doc/lcs/$MODULE /usr/share/doc/lcs-$MODULE
fi
# Fixation des droits sur l'arborescence du module
chown -R www-data:www-data /usr/share/lcs/desktop
chmod -R 755 /usr/share/lcs/desktop

