#! /bin/sh
set -e

MODULE="desktop"

case "$1" in
	purge|remove)
        #
        # Desinscription du module de la table lcs_db.applis
        #
        mysql -e "DELETE FROM lcs_db.applis WHERE name = '$MODULE';";
        invoke-rc.d apache2 force-reload
        ;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

#DEBHELPER#

exit 0