#!/bin/bash
# Simon CAVEY - CRDP de Basse-Normandie
# Projet LCS - Equipe TICE Académie de Caen
# Script de mise en place de la configuration ssh.
# /usr/sbin/lcs-openssh-config
if [ ! -e /etc/ssh/sshd_config.no-lcs ] ; then 
    mv /etc/ssh/sshd_config /etc/ssh/sshd_config.no-lcs
fi
if [ ! -e /etc/issue.net.no-lcs ] ; then
    mv /etc/issue.net /etc/issue.net.no-lcs
fi


cat >/etc/issue.net <<EOFISSUE
Bienvenue sur :
 _     ____ ____
| |   / ___/ ___|
| |  | |   \___ \\
| |__| |___ ___) |
|_____\____|____/

Linux Communication Server
http://lcs.crdp.ac-caen.fr

EOFISSUE

## fichier de config de SSH
cat >/etc/ssh/sshd_config <<EOF
# Package generated configuration file
# See the sshd(8) manpage for details

# What ports, IPs and protocols we listen for
Port 22
# Use these options to restrict which interfaces/protocols sshd will bind to
#ListenAddress ::
#ListenAddress 0.0.0.0
Protocol 2
# HostKeys for protocol version 2
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_dsa_key
#Privilege Separation is turned on for security
UsePrivilegeSeparation yes

# Lifetime and size of ephemeral version 1 server key
KeyRegenerationInterval 3600
ServerKeyBits 768

# Logging
SyslogFacility AUTH
LogLevel INFO

# Authentication:
LoginGraceTime 120
PermitRootLogin yes
StrictModes yes

RSAAuthentication yes
PubkeyAuthentication yes
#AuthorizedKeysFile     %h/.ssh/authorized_keys
#AuthorizedKeysFile     %h/.ssh/authorized_keys

# Don't read the user's ~/.rhosts and ~/.shosts files
IgnoreRhosts yes
# For this to work you will also need host keys in /etc/ssh_known_hosts
RhostsRSAAuthentication no
# similar for protocol version 2
HostbasedAuthentication no
# Uncomment if you don't trust ~/.ssh/known_hosts for RhostsRSAAuthentication
#IgnoreUserKnownHosts yes

# To enable empty passwords, change to yes (NOT RECOMMENDED)
PermitEmptyPasswords no

# Change to yes to enable challenge-response passwords (beware issues with
# some PAM modules and threads)
ChallengeResponseAuthentication no

# Change to no to disable tunnelled clear text passwords
#PasswordAuthentication yes

# Kerberos options
#KerberosAuthentication no
#KerberosGetAFSToken no
#KerberosOrLocalPasswd yes
#KerberosTicketCleanup yes

# GSSAPI options
#GSSAPIAuthentication no
#GSSAPICleanupCredentials yes

X11Forwarding no
X11DisplayOffset 10
AllowTcpForwarding no

PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
#UseLogin no

#MaxStartups 10:30:60
Banner /etc/issue.net

# Allow client to pass locale environment variables
AcceptEnv LANG LC_*

#Subsystem sftp /usr/lib/openssh/sftp-server
Subsystem       sftp     internal-sftp

UsePAM yes

Match user root
	AllowTcpForwarding yes

Match user spip.manager
          ChrootDirectory /usr/share/lcs/spip
          ForceCommand internal-sftp

Match user assist
	ChrootDirectory /home/%u
	AllowTcpForwarding yes
	ForceCommand internal-sftp

Match group sftp-allowed
          ChrootDirectory /home/%u
          ForceCommand internal-sftp

Match group admins
	ChrootDirectory /home/%u
        ForceCommand internal-sftp
	AllowTcpForwarding yes

Match group lcs-users
          ForceCommand /bin/false

EOF

## On creer le fichier de config pour le 2 ieme SSH 
cat >/etc/ssh/sshd_config_sftp <<EOFSSH2
# Package generated configuration file
# See the sshd(8) manpage for details

# What ports, IPs and protocols we listen for
Port 2222
# Use these options to restrict which interfaces/protocols sshd will bind to
#ListenAddress ::
#ListenAddress 0.0.0.0
Protocol 2
# HostKeys for protocol version 2
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_dsa_key
#Privilege Separation is turned on for security
UsePrivilegeSeparation yes

# Lifetime and size of ephemeral version 1 server key
KeyRegenerationInterval 3600
ServerKeyBits 768

# Logging
SyslogFacility AUTH
LogLevel INFO

# Authentication:
LoginGraceTime 120
PermitRootLogin no
StrictModes yes

RSAAuthentication yes
PubkeyAuthentication yes
#AuthorizedKeysFile     %h/.ssh/authorized_keys
#AuthorizedKeysFile     %h/.ssh/authorized_keys

# Don't read the user's ~/.rhosts and ~/.shosts files
IgnoreRhosts yes
# For this to work you will also need host keys in /etc/ssh_known_hosts
RhostsRSAAuthentication no
# similar for protocol version 2
HostbasedAuthentication no
# Uncomment if you don't trust ~/.ssh/known_hosts for RhostsRSAAuthentication
#IgnoreUserKnownHosts yes

# To enable empty passwords, change to yes (NOT RECOMMENDED)
PermitEmptyPasswords no

# Change to yes to enable challenge-response passwords (beware issues with
# some PAM modules and threads)
ChallengeResponseAuthentication no

# Change to no to disable tunnelled clear text passwords
#PasswordAuthentication yes

# Kerberos options
#KerberosAuthentication no
#KerberosGetAFSToken no
#KerberosOrLocalPasswd yes
#KerberosTicketCleanup yes

# GSSAPI options
#GSSAPIAuthentication no
#GSSAPICleanupCredentials yes

X11Forwarding no
X11DisplayOffset 10
AllowTcpForwarding no

PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
#UseLogin no

#MaxStartups 10:30:60
Banner /etc/issue.net

# Allow client to pass locale environment variables
AcceptEnv LANG LC_*

#Subsystem sftp /usr/lib/openssh/sftp-server
Subsystem       sftp     internal-sftp

UsePAM yes

Match user spip.manager
          ChrootDirectory /usr/share/lcs/spip
          ForceCommand internal-sftp

Match user assist
        ChrootDirectory /home/%u
        AllowTcpForwarding yes
        ForceCommand internal-sftp

Match group sftp-allowed
          ChrootDirectory /home/%u
          ForceCommand internal-sftp

Match group admins
        ChrootDirectory /home/%u
        ForceCommand internal-sftp
        AllowTcpForwarding yes

Match group lcs-users
          ForceCommand /bin/false

EOFSSH2


if [ -x /usr/sbin/invoke-rc.d ]; then
	invoke-rc.d ssh restart
else
	/etc/init.d/ssh restart
fi


## On ajoute lcs-sftp au boot
if [ -e /etc/init.d/lcs-sftp ] ; then 
    update-rc.d lcs-sftp defaults 17 17
    if [ -x /usr/sbin/invoke-rc.d ]; then
        invoke-rc.d lcs-sftp restart
    else
        /etc/init.d/lcs-sftp restart
    fi
    
fi



