<!-- Listing  pied.inc -->

<div id="pied"><?php
if (stripos($_SERVER['HTTP_USER_AGENT'], "msie"))  {
    echo '<img class="ie" src="../images/IE-no.png" alt="IE d&#233;conseill&#233;" title="L\'auteur d&#233;conseille l\'utilisation d\'Internet Explorer">';
}
    ?>Copyleft &#169; 2006 <?php echo $NAME_PLUG; ?>   version <?echo $VER_PLUG;?>&nbsp;

    <a href="http://validator.w3.org/check?uri=referer"><img
        src="http://www.w3.org/Icons/valid-xhtml10"
        alt="Valid XHTML 1.0 Strict" height="31" width="88"  /></a>
        
  </div>
