#! /bin/sh
set -e

case "$1" in
	purge|remove)
          # Drop directives for lcs-phpsysinfo
          rm -f /etc/apache2/lcs-main/65_phpsysinfo.conf
          invoke-rc.d apache2 force-reload
        ;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

#DEBHELPER#

exit 0