#!/bin/sh
set -e

case "$1" in
	install|configure)
            #
            # Mise en place du templates lcs
            #
            cp -a /var/lib/lcs/phpsysinfo/templates/lcs /usr/share/phpsysinfo/templates/
            #
            # Configuration
            #
            sed -i.bak s/\"en\"/\"fr\"/g /etc/phpsysinfo/config.php
            sed -i s/classic/lcs/g /etc/phpsysinfo/config.php
            #
            # only if first configuration
	    if [ "$2" = "" ]; then
	       . /usr/share/slis/slis-common.sh
	       handle_initial_config lcs-phpsysinfo-config 70
            fi
    	;;

    	abort-upgrade|abort-remove|abort-deconfigure)
    	;;

    	*)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    	;;
esac

exit 0