Document: lcs-anti-spam
Title: Debian lcs-anti-spam Manual
Author: <insert document author here>
Abstract: This manual describes what lcs-anti-spam is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lcs-anti-spam/lcs-anti-spam.sgml.gz

Format: postscript
Files: /usr/share/doc/lcs-anti-spam/lcs-anti-spam.ps.gz

Format: text
Files: /usr/share/doc/lcs-anti-spam/lcs-anti-spam.text.gz

Format: HTML
Index: /usr/share/doc/lcs-anti-spam/html/index.html
Files: /usr/share/doc/lcs-anti-spam/html/*.html

  
