Document: lcs-imap-ssl
Title: Debian lcs-imap-ssl Manual
Author: <insert document author here>
Abstract: This manual describes what lcs-imap-ssl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lcs-imap-ssl/lcs-imap-ssl.sgml.gz

Format: postscript
Files: /usr/share/doc/lcs-imap-ssl/lcs-imap-ssl.ps.gz

Format: text
Files: /usr/share/doc/lcs-imap-ssl/lcs-imap-ssl.text.gz

Format: HTML
Index: /usr/share/doc/lcs-imap-ssl/html/index.html
Files: /usr/share/doc/lcs-imap-ssl/html/*.html

  
