
<select id="player" size="0" style="border:1px solid gray; color:gray;" onchange="player_n.value = player.value">
<option> </option>
<option>Adams</option>
<option>Adorjan</option>
<option>Akopian</option>
<option>Alekhine</option>
<option>Almasi</option>
<option>Anand</option>
<option>Anderssen</option>
<option>Andersson</option>
<option>Aronian</option>
<option>Averbakh</option>
<option>Azmaiparashvili</option>
<option>Bacrot</option>
<option>Balashov</option>
<option>Bareev</option>
<option>Beliavsky</option>
<option>Benjamin</option>
<option>Blackburne</option>
<option>Blatny</option>
<option>Bogoljubov</option>
<option>Bologan</option>
<option>Botvinnik</option>
<option>Bronstein</option>
<option>Capablanca</option>
<option>Chandler</option>
<option>Chiburdanidze</option>
<option>Chigorin</option>
<option>Christiansen</option>
<option>Dreev</option>
<option>Epishin</option>
<option>Euwe</option>
<option>Filip</option>
<option>Fine</option>
<option>Fischer</option>
<option>Ftacnik</option>
<option>Gelfand</option>
<option>Geller</option>
<option>Georgiev</option>
<option>Gligoric</option>
<option>Grischuk</option>
<option>Gruenfeld</option>
<option>Gulko</option>
<option>Gurevich</option>
<option>Hodgson</option>
<option>Hort</option>
<option>Huebner</option>
<option>Ivanchuk</option>
<option>Ivkov</option>
<option>Janowski</option>
<option>Jansa</option>
<option>Jiangchuan</option>
<option>Jun</option>
<option>Kamsky</option>
<option>Karpov</option>
<option>Kasimdzhanov</option>
<option>Kasparov</option>
<option>Keene</option>
<option>Keres</option>
<option>Khalifman</option>
<option>Kharlov</option>
<option>Kholmov</option>
<option>Korchnoi</option>
<option>Kotov</option>
<option>Kramnik</option>
<option>Krasenkow</option>
<option>Kupreichik</option>
<option>Larsen</option>
<option>Lasker</option>
<option>Lautier</option>
<option>Leko</option>
<option>Ljubojevic</option>
<option>Macieja</option>
<option>Malakhov</option>
<option>Mamedyarov</option>
<option>Marshall</option>
<option>Matulovic</option>
<option>Miles</option>
<option>Milov</option>
<option>Morozevich</option>
<option>Morphy</option>
<option>Movsesian</option>
<option>NN</option>
<option>Najdorf</option>
<option>Navara</option>
<option>Nezhmetdinov</option>
<option>Nielsen</option>
<option>Nikolic</option>
<option>Nimzowitsch</option>
<option>Nisipeanu</option>
<option>Nunn</option>
<option>Onischuk</option>
<option>Paulsen</option>
<option>Pavasovic</option>
<option>Petrosian</option>
<option>Philidor</option>
<option>Piket</option>
<option>Pillsbury</option>
<option>Plachetka</option>
<option>Polgar</option>player_n
<option>Polugaevsky</option>
<option>Ponomariov</option>
<option>Portisch</option>
<option>Psakhis</option>
<option>Radjabov</option>
<option>Razuvaev</option>
<option>Reshevsky</option>
<option>Reti</option>
<option>Romanishin</option>
<option>Rozentalis</option>
<option>Rubinstein</option>
<option>Rublevsky</option>
<option>Sakaev</option>
<option>Salov</option>
<option>Samisch</option>
<option>Sasikiran</option>
<option>Savon</option>
<option>Schlechter</option>
<option>Schmidt</option>
<option>Seirawan</option>
<option>Shabalov</option>
<option>Shirov</option>
<option>Short</option>
<option>Smejkal</option>
<option>Smirin</option>
<option>Smyslov</option>
<option>Sokolov</option>
<option>Spassky</option>
<option>Speelman</option>
<option>Spielmann</option>
<option>Spraggett</option>
<option>Staunton</option>
<option>Steinitz</option>
<option>Sutovsky</option>
<option>Svidler</option>
<option>Szabo</option>
<option>Taimanov</option>
<option>Tal</option>
<option>Tarrasch</option>
<option>Tartakower</option>
<option>Teichmann</option>
<option>Timman</option>
<option>Timoshchenko</option>
<option>Tiviakov</option>
<option>Topalov</option>
<option>Tseshkovsky</option>
<option>Tukmakov</option>
<option>Uhlmann</option>
<option>Vaganian</option>
<option>Vallejo-Pons</option>
<option>Van</option>
<option>Vasiukov</option>
<option>Velimirovic</option>
<option>Vidmar</option>
<option>Yermolinsky</option>
<option>Yudasin</option>
<option>Yusupov</option>
</select>
