#!/bin/sh

# /usr/sbin/lcs-web-config

set -e
exit_fatal() {
	echo "Fatal: $1" >&2
	exit 0
}

. /usr/share/slis/slis-common.sh

# Load LCS config
[ ! -e /etc/lcs/lcs.conf ] && exit_fatal "missing /etc/lcs/lcs.conf"
. /etc/lcs/lcs.conf

case "$1" in
    possible)
        # Is the LDAP server reachable ?
        if pgrep -u mysql mysqld >/dev/null && ldapsearch -x "(uid=admin)($LDAP_BASE_DN)" 2>/dev/null | grep -q "^dn: "; then
            exit 0
        else
            exit 1
        fi
    ;;
    needed)
	exit 0
    ;;
    configure)
        # Configure LCS Web
        #
        # Add LCS profile conf in etc
        mv /etc/profile /etc/profile.lcsav
        cp /var/lib/lcs/web/profile /etc/profile
        # Patch /etc/skel/public_html/index.html.in
        sed -e "s/##HOST##/$DOMAIN/g" /etc/skel/public_html/index.html.in \
	    >/etc/skel/public_html/index.html
        # Patch files /etc/LcSeConfig.php.in /var/www/index.html.in /var/www/lcs/includes/config.inc.in 
        echo "Patch des fichiers de conf LCS"
        sed -e "s|@@PASSWORD@@|"$MYSQLPW"|g" /etc/LcSeConfig.ph.in >/etc/LcSeConfig.ph
        chmod 640 /etc/LcSeConfig.ph
        chown root:www-data /etc/LcSeConfig.ph
        sed -e "s|@@PASSWORD@@|"$LCSMGRPASS"|g" /var/www/lcs/includes/config.inc.in >/var/www/lcs/includes/config.inc.php
        chown www-data:www-data /var/www/lcs/includes/config.inc.php

        # Réinitialisation password account admin lcs if initial install
	echo "Réinitialisation du mpd du compte admin lcs"
	/usr/share/lcs/sbin/userChangePwd.pl admin admin

        # Add right stats_can_read
        if ! ldapsearch -x "(cn=stats_can_read)($LDAP_BASE_DN)" 2>/dev/null | grep -q "^dn: "; then
            echo "dn: cn=stats_can_read,ou=Rights,$LDAP_BASE_DN
objectClass: groupOfNames
cn: stats_can_read
member: uid=admin,ou=People,$LDAP_BASE_DN" > /var/lib/lcs/stats_can_read.ldif
            ldapadd -x -D "cn=$LDAP_ADMIN_RDN,$LDAP_BASE_DN" -w $LDAP_ADMIN_PW -f /var/lib/lcs/stats_can_read.ldif
            rm -f /var/lib/lcs/stats_can_read.ldif
        fi

        # Create webmaster.etab account
        if ! getent passwd webmaster.etab >/dev/null; then
            echo "Creation compte webmaster.etab"
            sed -e "s|#PEOPLE#|$LDAP_PEOPLE_RDN|g" \
                -e "s|#BASEDN#|$LDAP_BASE_DN|g" \
                -e "s|#MAILDOMAIN#|$LDAP_MAIL_DOMAIN|g" \
                /var/lib/lcs/web/ldif/webmasteretab.ldif.in > /var/lib/lcs/web/ldif/webmasteretab.ldif
            ldapadd -x -D "cn=$LDAP_ADMIN_RDN,$LDAP_BASE_DN" -w $LDAP_ADMIN_PW -f /var/lib/lcs/web/ldif/webmasteretab.ldif
#            UIDPOLICY=`mysql -se "select value from lcs_db.params where name='uidpolicy';"`
#            mysql -se "UPDATE lcs_db.params SET value = '1' WHERE name = 'uidpolicy';"
#            /usr/share/lcs/sbin/userAdd.pl Webmaster Etab `pwgen -1 -s` 20081212 M Profs
#            #force uid to 5001
#            echo "dn: uid=webmaster.etab,ou=People,$LDAP_BASE_DN
#changetype : modify
#replace : uidnumber
#uidnumber : 5001" > /var/lib/lcs/uid_admin.ldif
#            ldapmodify -x -D "cn=$LDAP_ADMIN_RDN,$LDAP_BASE_DN" -w $LDAP_ADMIN_PW -f /var/lib/lcs/uid_admin.ldif
#            rm -f /var/lib/lcs/uid_admin.ldif
#            # ReInstallation original uidpolicy 
#            mysql -se "UPDATE lcs_db.params SET value = '$UIDPOLICY' WHERE name = 'uidpolicy';"
            if [ ! -d /home/webmaster.etab ];then
                mkdir /home/webmaster.etab
            fi
            chown webmaster.etab:www-data /home/webmaster.etab
            chmod 770 /home/webmaster.etab
            cp -a /etc/skel/* /home/webmaster.etab/
            chown -R webmaster.etab:www-data /home/webmaster.etab/public_html
            chown -R webmaster.etab:www-data /home/webmaster.etab/Maildir
            chmod -R 700 /home/webmaster.etab/Maildir
        fi
        #
        # dir.conf
        #
        echo "mise en place dir.conf"
        cp /var/lib/lcs/web/apache2/dir.conf.in /etc/apache2/mods-available/dir.conf
        chmod 644 /etc/apache2/mods-available/dir.conf
        #
        # Desactivate lcs virtualhost of interfacedu-lcs
        #
        echo "Mise en place virtualhosts"
        a2dissite lcs > /dev/null 2>&1

        # Installation real lcs virtualhost 
        LCSFULLDOMAIN="$HOSTNAME.$DOMAIN"
        sed -e "s/#LCSDOMAIN#/$DOMAIN/g" \
	    -e "s/#LCSFULLDOMAIN#/$LCSFULLDOMAIN/g" \
	    -e "s/#IPADDR0#/$IPADDR0/g" \
	    /var/lib/lcs/web/apache2/virtualhost.lcs.in \
	    >/etc/apache2/sites-available/$LCSFULLDOMAIN
        a2ensite $LCSFULLDOMAIN

        # Installation www.#DOMAIN# virtualhost 
        sed -e "s/#IPADDR0#/$IPADDR0/g" \
            -e "s/#LCSDOMAIN#/$DOMAIN/g" \
	    /var/lib/lcs/web/apache2/virtualhost.www.in
	    >/etc/apache2/sites-available/www.$DOMAIN
        a2ensite www.$DOMAIN

        # Installation menu.d if not present
        if [ ! -d /var/www/lcs/includes/menu.d ]; then
            cp -r /var/lib/lcs/web/menu.d /var/www/lcs/includes
        fi

        # Installation files common files lcs and monlcs 
	cp /var/lib/lcs/web/varwwwlcs/*.php /var/www/lcs/

        # Configuration webalizer
        echo "Configuration webalizer"
        sed -e "s/#HOSTNAME#/`hostname`/g" /var/lib/lcs/web/webalizer/webalizer.conf.in >/etc/webalizer/webalizer.conf

        # restart apache2
        invoke-rc.d apache2 restart
    ;;
    *)
        echo "usage: $0 {configure|possible|needed}" >&2
        exit 1
    ;;
esac
