#!/bin/bash
#
# Fix rights on web tree
#
echo "lcs-web fix rights"
#
chown root:root /etc/LcSeConfig.ph.in
chown root:root /etc/profile
chown root:root /etc/lcs/sudo.d/01-lcs-web
# /var/www
chown root:root /var/www
chmod 755 /var/www
chown -R root:www-data /var/www/*
chmod -R 750 /var/www/* 
chown www-data /var/www/import
chmod -R 770 /var/www/lcs/includes/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer
# /usr/share/lcs
chown root:www-data /usr/share/lcs
chmod 750 /usr/share/lcs
chown -f root:www-data /usr/share/lcs/Plugins
chown -Rf root:www-data /usr/share/lcs/Modules
chown -Rf www-data:www-data /usr/share/lcs/privatekey
chmod 600 /usr/share/lcs/privatekey/privateKey.py
chmod 644 /usr/share/lcs/privatekey/decode.py
chmod 750 /usr/share/lcs/*
chown root:www-data /usr/share/lcs/*
#sbin
chmod 750 /usr/share/lcs/sbin/*
chown -R root:www-data /usr/share/lcs/sbin/*
chown root:root /usr/share/lcs/sbin/webmasterCorrect.pl
chown root:root /usr/share/lcs/sbin/CaenDeploy.sh
#scripts
chmod 750 /usr/share/lcs/scripts/*
chown root:www-data /usr/share/lcs/scripts/*
# cgi
chown root:root /usr/lib/cgi-bin
chmod 750 /usr/lib/cgi-bin
#chown root:www-data /usr/lib/cgi-bin/gep2.cgi
#chmod 750 /usr/lib/cgi-bin/gep2.cgi

#
chown root:root /usr/sbin/LcsMaj
chmod 700 /usr/sbin/LcsMaj
#
mkdir -p /var/log/lcs
chown www-data /var/log/lcs
chmod 750 /var/log/lcs
#
mkdir -p  /var/lib/lcs/import_comptes
chown www-data:root /var/lib/lcs/import_comptes
chmod 755 /var/lib/lcs/import_comptes
# Clean old install
rm -Rf /usr/share/lcs/Plugins/Logs


