#!/bin/bash
#
# Fixation des droits sur les arborescences LCS web
#
chown root:root /etc/LcSeConfig.ph.in
chown root:root /etc/profile
chown root:root /etc/lcs/sudo.d/01-lcs-web

chown root:root /var/www
chown -Rf www-data:www-data /var/www/Admin
chown -Rf www-data:www-data /var/www/Annu
chown -Rf www-data:www-data /var/www/c
chown -Rf www-data:www-data /var/www/Err
chown -Rf www-data:www-data /var/www/images
chown -Rf www-data:www-data /var/www/lcs
chown -Rf www-data:www-data /var/www/setup
chown -Rf www-data:www-data /var/www/Usingstats
chown -f www-data:www-data /var/www/index.html
chown -f www-data:www-data /var/www/style.css

chown root:root /usr/lib/cgi-bin
chmod 755 /usr/lib/cgi-bin
chown root:www-data /usr/lib/cgi-bin/gep2.cgi
chmod 750 /usr/lib/cgi-bin/gep2.cgi

chown root:root /usr/share/lcs
chown -Rf www-data:www-data /usr/share/lcs/Plugins
chown -Rf www-data:www-data /usr/share/lcs/Modules
chown -Rf www-data:www-data /usr/share/lcs/privatekey
chmod 600 /usr/share/lcs/privatekey/privateKey.py
chmod 644 /usr/share/lcs/privatekey/decode.py

chown root:root /usr/share/lcs/sbin
chmod 750 /usr/share/lcs/sbin/*
chown -R root:www-data /usr/share/lcs/sbin/*
chown root:root /usr/share/lcs/sbin/webmasterCorrect.pl
chown root:root /usr/share/lcs/sbin/CaenDeploy.sh

chown root:root /usr/share/lcs/scripts
chmod 700 /usr/share/lcs/scripts/*
chown root:root /usr/share/lcs/scripts/*
chown www-data:www-data /usr/share/lcs/scripts/*.php
chown www-data:www-data /usr/share/lcs/scripts/execution_script_plugin.sh
chown www-data:www-data /usr/share/lcs/scripts/gestpack.sh
chown www-data:www-data /usr/share/lcs/scripts/ntlmpass.pl
chown www-data:www-data /usr/share/lcs/scripts/unixPassword.pl

chown root:root /usr/sbin/LcsMaj
chmod 700 /usr/sbin/LcsMaj

mkdir -p /var/log/lcs
chown www-data /var/log/lcs
chmod 750 /var/log/lcs

mkdir -p  /var/lib/lcs/import_comptes
chown www-data:root /var/lib/lcs/import_comptes
chmod 755 /var/lib/lcs/import_comptes
