#!/bin/bash
#Couleurs
COLTITRE="\033[1;35m"          # Rose
COLCMD="\033[1;37m"            # Blanc
COLQUESTION="\033[1;32m"       # Vert

if  ! egrep -q "^5.0" /etc/debian_version;  then
        if egrep -q "^6.0" /etc/debian_version; then
                echo "Votre serveur est deja en version Debian Squeeze"
                exit 0
        else
                echo "Votre serveur n'est pas en version Debian Lenny."
                echo "Operation annulee !"
                exit 1
        fi
fi


echo -e "$COLTITRE"
echo "******************************"
echo "* Migration Lenny vers Squeeze  *"
echo "******************************"
echo -e "$COLQUESTION\c"
echo "Voulez vous continuez (O/n) ? "
echo -e "$COLCMD\c"
read REPLY
if [ "$REPLY" != "O" ] &&  [ "$REPLY" != "o" ] && [ -n $REPLY ]; then
        echo "Pas de migration !"
        exit 1
fi

echo -e "$COLTITRE"
echo "Migration LCS de Debian Lenny vers Squeeze"
echo -e "$COLCMD\c"
#######
echo "1. Detection de la branche LCS : Lcs, LcsTesting, LcsXP"

if grep LcsXP /etc/apt/sources.list; then
        LCSTREE="LcsXP"
elif grep LcsTesting /etc/apt/sources.list; then
        LCSTREE="LcsTesting"
else
        LCSTREE="Lcs"
fi
echo "Votre LCS est sur la branche :  $LCSTREE"
#######
echo "2. Changement du source list"

cp /etc/apt/sources.list /etc/apt/sources.list.lenny

echo "deb http://ftp.fr.debian.org/debian squeeze main
deb-src http://ftp.fr.debian.org/debian squeeze main

##deb http://lcs.crdp.ac-caen.fr/squeeze $LCSTREE main

#deb http://security.debian.org/ squeeze/updates main
#deb-src http://security.debian.org/ squeeze/updates main

#deb http://volatile.debian.org/debian-volatile squeeze/volatile main
#deb-src http://volatile.debian.org/debian-volatile squeeze/volatile main" > /etc/apt/sources.list
#######
echo "3. Test si on enleve pas des paquets LCS !"
aptitude update
if aptitude dist-upgrade -s -y | grep Remv | grep lcs; then
        echo "Migration LENNY -> SQUEEZE interrompue par tentative de desinstallation des paquets LCS"
        exit 1
fi
### On demande a garder les fichiers de config.
cat > /etc/apt/apt.conf.d/lcs-upgrade-squeeze <<EOF
Dpkg::Options {
"--force-confdef";
"--force-confold";
}
EOF


### On repond aux questions avant qu'elles n'arrivent.
cat > /tmp/preseed-squeeze <<EOF
# Faut-il garder le fichier de configuration de libnss-ldap automatiquement ?
libnss-ldap     libnss-ldap/override    boolean false
# Faut-il garder la configuration automatiquement ?
libpam-ldap     libpam-ldap/override    boolean false
# Services a redemarrer lors de la mise a  niveau de la bibliotheque PAM :
#libpam0g        libpam0g/restart-services       string  squid cron courier-authdaemon atd
# Choices: Belgian, French
console-data    console-data/keymap/azerty/layout       select
bind9  bind9/start-as-user     string  bind
#libc6  glibc/restart-services  string  slapd rsync postfix openbsd-inetd cron courier-authdaemon atd
libssl0.9.8    libssl0.9.8/restart-services    string  ssh
# For squeeze
libc6   glibc/restart-services  string  postfix openbsd-inetd mysql cron courier-authdaemon apache2
dash    dash/sh boolean true
libpam0g        libpam0g/restart-services       string  cron courier-authdaemon atd
sysv-rc sysv-rc/convert-legacy  boolean true
libpam-runtime  libpam-runtime/override boolean false
linux-base      linux-base/disk-id-manual-boot-loader   error
linux-base      linux-base/disk-id-update-failed        error
linux-base      linux-base/disk-id-manual       error
linux-base      linux-base/disk-id-convert-plan-no-relabel      boolean true
linux-base      linux-base/disk-id-convert-auto boolean true
linux-base      linux-base/do-bootloader-default-changed        error
linux-base      linux-base/disk-id-convert-plan boolean true
# Grub
grub    grub/migrate_from_legacy        note
grub-pc grub2/kfreebsd_cmdline  string
# Recréation de /boot/grub/device.map
grub-pc grub2/device_map_regenerated    note
grub-pc grub2/linux_cmdline     string
grub-pc grub-pc/install_devices_empty   boolean false
grub-pc grub-pc/install_devices_failed  boolean false
grub-pc grub-pc/chainload_from_menu.lst boolean true
grub-pc grub-pc/kopt_extracted  boolean true
grub-pc grub-pc/install_devices multiselect
# Faut-il supprimer GRUB 2 de /boot/grub ?
grub-pc grub-pc/postrm_purge_boot_grub  boolean false
grub-pc grub-pc/install_devices_failed_upgrade  boolean true
grub-pc grub2/kfreebsd_cmdline_default  string  quiet
grub-pc grub-pc/install_devices_disks_changed   multiselect
grub-pc grub2/linux_cmdline_default     string  quiet
grub-pc grub-pc/mixed_legacy_and_grub2  boolean true
# debconf
debconf	debconf/frontend	select	Noninteractive
debconf	debconf/priority	select	critical

EOF

debconf-set-selections < /tmp/preseed-squeeze   
#######
echo "4. Nettoyage DB_CONFIG et sauvegarde slapd.conf."
mkdir /root/migresqueeze
slapcat > /root/migresqueeze/ldaplcslenny.ldif
cat /var/lib/ldap/DB_CONFIG | grep -v "sactivation logs ldap" > /root/migresqueeze/DB_CONFIG
cp /root/migresqueeze/DB_CONFIG /var/lib/ldap/DB_CONFIG
cp /etc/ldap/slapd.conf /root/migresqueeze/

echo "5. Upgrade de la distribution (Fournir les reponses par defaut)."
aptitude update
echo "5.1 Upgrade des paquets de base : libc6, locales et mysql-server (Fournir les reponses par defaut)."
aptitude install -y libc6 locales mysql-server
echo "5.2 Upgrade de la distribution par dist-upgrade (Fournir les reponses par defaut)."
aptitude dist-upgrade -y
sed -i 's|^#||g' /etc/apt/sources.list
aptitude update
aptitude dist-upgrade -y
echo "5.3 Test du service Mysql avant mise a jour LCS"
if  ! mysqladmin --defaults-file=/etc/mysql/debian.cnf ping > /dev/null 2>&1 ; then
        echo "mysql NOK"
        /etc/init.d/mysql start
fi

if  ! mysqladmin --defaults-file=/etc/mysql/debian.cnf ping > /dev/null 2>&1 ; then
        echo "ERREUR : Le service Mysql ne demarre pas... Mise a jour LCS interrompue !"
        exit 1
fi
echo "6. Preparation service slapd avant mise à lour LCS ldapedu-server..."
/ect/init.d/slapd stop
sed -i "s/#SLAPD_CONF=/SLAPD_CONF=\"\/etc\/ldap\/slapd.conf\"/g" /etc/default/slapd
cp /root/migresqueeze/slapd.conf /etc/ldap/slapd.conf
chown openldap:openldap /etc/ldap/slapd.conf
/ect/init.d/slapd start

echo "7. Mise a jour LCS"
sed -i 's|#||g' /etc/apt/sources.list
aptitude update
aptitude dist-upgrade -y
#######
echo "8. Mise a jour des droits sur les repertoires MAILDIR"
for MAILDIR in `find /home -name Maildir`
do
        echo "$MAILDIR"
        chgrp -R lcs-users $MAILDIR
done
#######
echo "9. Mise en place de lcs-sysinfo en remplacement de lcs-phpsysinfo"
apt-get install -y --force-yes lcs-sysinfo

echo "10. Modification du referentiel des modules" 
mysql -e "UPDATE lcs_db.params SET value = 'http://linux.crdp.ac-caen.fr/modulesLcsqueeze/' WHERE value = 'http://linux.crdp.ac-caen.fr/modulesLennycs/';" 
mysql -e "UPDATE lcs_db.params SET value = 'http://linux.crdp.ac-caen.fr/modulesLcsqueezeTesting/' WHERE value ='http://linux.crdp.ac-caen.fr/modulesLennycsTesting/';"
mysql -e "UPDATE lcs_db.params SET value = 'http://linux.crdp.ac-caen.fr/modulesLcsqueezeXP/' WHERE value = 'http://linux.crdp.ac-caen.fr/modulesLennycsXP/';"

echo "11. Redemarrage service ldap suite a la mise a jour"
/ect/init.d/slapd stop
/ect/init.d/slapd start

rm /etc/apt/apt.conf.d/lcs-upgrade-squeeze
echo -e "$COLTITRE"
echo "FIN !"
echo -e "$COLCMD\c"
