#!/bin/bash
# /usr/sbin/LcsMaj version du 12-06-2010
PATH="/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/share/lcs/sbin:/usr/share/lcs/scripts"
#
# Mise a jour des paquets logiciels du serveur si mysql repond
#
if  mysqladmin --defaults-file=/etc/mysql/debian.cnf ping > /dev/null 2>&1 ; then
    DEBIAN_PRIORITY="critical"
    DEBIAN_FRONTEND="noninteractive"
    export  DEBIAN_FRONTEND
    export  DEBIAN_PRIORITY
    apt-get update
    apt-get -y install mysql-server
    apt-get -y --force-yes dist-upgrade
    DEBIAN_PRIORITY="high"
    DEBIAN_FRONTEND="dialog"
    export  DEBIAN_PRIORITY
    export  DEBIAN_FRONTEND
else
    echo "Service Mysql inaccessible, report de la mise a jour systeme."
    exit 1
fi
