#! /bin/sh

# postinst script for lcs-lightsquid

set -e

case "$1" in
    configure)
	chmod +x /usr/share/lcs/lightsquid/*.pl
	chmod +x /usr/share/lcs/lightsquid/*.cgi
	chown -R www-data:www-data /usr/share/lcs/lightsquid
	chown www-data:www-data /var/www/lcs/includes/mnu.d/50stats/40lightsquid.inc
	# Reload apache conf
    /etc/init.d/apache2 reload > /dev/null 2>&1
    	;;

    abort-upgrade|abort-remove|abort-deconfigure)
    	;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    	;;
esac

#DEBHELPER#

exit 0
