Document: lcs-jabber
Title: Debian lcs-jabber Manual
Author: <insert document author here>
Abstract: This manual describes what lcs-jabber is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lcs-jabber/lcs-jabber.sgml.gz

Format: postscript
Files: /usr/share/doc/lcs-jabber/lcs-jabber.ps.gz

Format: text
Files: /usr/share/doc/lcs-jabber/lcs-jabber.text.gz

Format: HTML
Index: /usr/share/doc/lcs-jabber/html/index.html
Files: /usr/share/doc/lcs-jabber/html/*.html


