#! /bin/sh
### BEGIN INIT INFO
# Provides: rubycas-server
# Required-Start: $syslog
# Should-Start:
# Required-Stop:  $syslog
# Should-Stop:
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    Start the RubyCAS-Server
### END INIT INFO

#
# System startup script for the rubycas-server
#



CASSERVER='/var/lib/gems/1.8/gems/rubycas-server-1.1.2/bin'
CONFFILE="/etc/rubycas-server/config.yml"
USERRUN="casserver"

cd $CASSERVER

case "$1" in
    start)
		su -c "ruby rubycas-server-control start" $USERRUN
        ;;
    stop)
		su -c "ruby rubycas-server-control stop" $USERRUN
        ;;
    restart)
		su -c "ruby rubycas-server-control restart" $USERRUN
        ;;
    status)
		su -c "ruby rubycas-server-control status" $USERRUN      
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1
        ;;
esac

