#! /bin/sh
#
# System startup script for the rubycas-server
#

CASSERVER='/var/lib/gems/1.8/gems/rubycas-server-0.7.999999.20100202/bin/rubycas-server'
PIDFILE="/var/run/rubycas-server/casserver.pid"
CONFFILE="/etc/rubycas-server/config.yml"
USERRUN="casserver"
LOGCASSERVER="/var/log/rubycas-server/casserver.log"
TIME=$(date +"%Y-%m-%dT%H:%M:%S")

stopcasserver() {
	if [ -e $PIDFILE ]; then
        	PIDPROCESS=`cat $PIDFILE`
        	kill -9 $PIDPROCESS
        	echo "I, [$TIME #$PIDPROCESS] INFO -- : Stoping CASServer as a WEBrick daemon with process id $PIDPROCESS" >> $LOGCASSERVER
        	rm -f $PIDFILE
			echo "rubycas-server is stopped."
	fi
}

startcasserver() {
	if [ ! -e $PIDFILE ]; then
		su -c "$CASSERVER -d -c $CONFFILE -P $PIDFILE" $USERRUN 1>/dev/null
		if [ -e $PIDFILE ]; then
			PIDPROCESS=`cat $PIDFILE`
			echo "rubycas-server start and running with pid:$PIDPROCESS"
		else
			echo "ERR : rubycas-server will not start !"
		fi
	else
		PIDPROCESS=`cat $PIDFILE`
		echo "rubycas-server appears to be up and running (pid:$PIDPROCESS)."
	fi
}



case "$1" in
    start)
		startcasserver
        ;;
    stop)
		stopcasserver
        ;;
    restart)
		stopcasserver
        startcasserver
        ;;
    status)
    	if [ -e $PIDFILE ]; then
        	PIDPROCESS=`cat $PIDFILE`    	
    		echo "rubycas-server appears to be up and running (pid:$PIDPROCESS)."
    	else	
        	echo "rubycas-server does not appear to be running (pid file not found)."
        fi        
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1
        ;;
esac

