<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseCasSt extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cas_st');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('ticket', 'string', 255, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('service', 'string', 2147483647, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '2147483647'));
        $this->hasColumn('client_hostname', 'string', 255, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('username', 'string', 255, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('type', 'string', 255, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('consumed', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
        $this->hasColumn('proxy_granting_ticket_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('tgt_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    }

    public function setUp()
    {
        $this->hasOne('CasTgt', array('local' => 'tgt_id',
                                      'foreign' => 'id',
                                      'onDelete' => 'CASCADE'));

        $this->hasMany('CasserverPgt as CasSts', array('local' => 'id',
                                                       'foreign' => 'service_ticket_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}