<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseCasserverPgt extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cas_pgt');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('ticket', 'string', 255, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('client_hostname', 'string', 255, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('iou', 'string', 255, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('service_ticket_id', 'integer', 4, array('type' => 'integer', 'default' => '', 'notnull' => true, 'length' => '4'));
    }

    public function setUp()
    {
        $this->hasOne('CasSt', array('local' => 'service_ticket_id',
                                     'foreign' => 'id',
                                     'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}