#! /bin/sh

set -e

# lecture d'un parametre lcs dans lcs_db.params
get_lcsdb_params() {
mysqlpass=`cat /var/www/lcs/includes/config.inc.php | grep PASSAUTH= | cut -d = -f 2 | cut -d \" -f 2`
PARAMS=`echo  "SELECT value FROM params WHERE name='$1'"| mysql -u lcsmgr -p$mysqlpass lcs_db -N`
echo "$PARAMS"
}

configure() {
    FQN=`hostname -f`
    DOMAIN=$(get_lcsdb_params domain)
    VLANSC=$(get_lcsdb_params vlansc)
    VLANADMINISTRATIF=$(get_lcsdb_params vlanadmin)
    VLANPEDA1=$(get_lcsdb_params vlanpeda1)
    VLANPEDA2=$(get_lcsdb_params vlanpeda2)
    VLANPEDA3=$(get_lcsdb_params vlanpeda3)
    VLANPEDA4=$(get_lcsdb_params vlanpeda4)
    LAN_NETWORKS_TMP="$VLANSC $VLANADMINISTRATIF $VLANPEDA1 $VLANPEDA2 $VLANPEDA3 $VLANPEDA4"
    LAN_NETWORKS=`echo $LAN_NETWORKS_TMP | sed -e "s/ /,/g"`
    LDAP_BASE_DN=$(get_lcsdb_params ldap_base_dn)
    RELAY_HOST=$(get_lcsdb_params relayhost)
    # postfix_reconfigure.sh <FQDN> <DOMAIN> <LOCAL_DOMAIN> <NETWORK> <BASEDN> <RELAYHOST> <XEN_NETWORK>"
    /usr/share/lcs/scripts/postfix_reconfigure.sh "$FQN" "$DOMAIN" "" "$LAN_NETWORKS" "$LDAP_BASE_DN" "$RELAY_HOST"
    newaliases
}

case "$1" in
    possible)
	if pgrep -u mysql mysqld >/dev/null; then
	    exit 0
	else
	    exit 1
	fi
    ;;
    needed)
	exit 0
    ;;
    configure)
	configure
    ;;
    "")
	if $0 possible && $0 needed; then
	    $0 configure
	fi
    ;;
esac

