#! /bin/sh
# postinst script for LCS Roundcube
set -e

case "$1" in
	install|configure)
		if [ "$2" = "" ]; then
			# on each configuration
			. /usr/share/slis/slis-common.sh
				handle_initial_config lcs-roundcube-config 95
		else
			# Update Roundcube
			echo "Update Roundcube."
			/usr/sbin/lcs-roundcube-update
		fi
    	;;

    	abort-upgrade|abort-remove|abort-deconfigure)
    	;;

    	*)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    	;;
esac

#DEBHELPER#

exit 0
