<?
$liens1=array(array(
        "Statistiques","system_is_admin",
	"Moniteur Syst&#232;me","../phpsysinfo/","system_is_admin",
        "Serveur web Intranet","../webalizer/","system_is_admin",
#	"Mandataire cache","../squid-reports/","system_is_admin",
	"Log redirection mails","/Admin/mail_rediriges.php","lcs_is_admin",
	"Statistiques d'usage","../Usingstats/statusage.php","system_is_admin",
));
$liens=array_merge($liens,$liens1);    
?>