#! /bin/sh
# postrm script for LCS squid

set -e
case "$1" in
	purge|remove)
        iptables -t nat -F
        if [ "$1" == "purge" ];then
            if [ -e /etc/lcs/squid/squid.conf ];then
                rm /etc/lcs/squid/squid.conf
            fi
            rm -f /etc/rc2.d/S12iptables
        fi
        ;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

exit 0
