#!/bin/bash

        cd /root
        ARCHIVE_FILE="ecran_securite.php"
        ARCHIVE_FILE_MD5="ecran_securite.md5"
        SCRIPTS_DIR="/usr/share/lcs/spip/config/"

        rm -f $ARCHIVE_FILE_MD5 $ARCHIVE_FILE

        wget -N -q --tries=1 --connect-timeout=1 http://svn.tice.ac-caen.fr/svn/LcsSE3/LCS/spipecransecu/$ARCHIVE_FILE
        wget -N -q --tries=1 --connect-timeout=1 http://svn.tice.ac-caen.fr/svn/LcsSE3/LCS/spipecransecu/$ARCHIVE_FILE_MD5
        MD5_CTRL=$(cat $ARCHIVE_FILE_MD5)
        MD5_CTRL_LOCAL=$(md5sum $ARCHIVE_FILE)

        if [ "$MD5_CTRL" != "$MD5_CTRL_LOCAL" ]
        then    
                echo "Controle MD5 de l'archive incorrecte, pas de mis en place d'un nouvel ecran de securite"
                exit 1
        fi

        cd $SCRIPTS_DIR

        MD5_CTRL_LOCAL1=$(md5sum $ARCHIVE_FILE)
        cd -
        MD5_CTRL1=$(cat $ARCHIVE_FILE_MD5)

        if [ "$MD5_CTRL1" != "$MD5_CTRL_LOCAL1" ]; then
                echo "Mise en place nouvel ecran de securite"
                cp $ARCHIVE_FILE $SCRIPTS_DIR
        else
                echo "Version a jour, pas de mise en place  d'un nouvel ecran de securite"
        fi


