#! /bin/sh
# postrm script for LCS CAS

set -e

MODULE="cas"
PIDFILE="/var/run/rubycas-server/casserver.pid"

case "$1" in
	purge|remove)
        #
        # unsubscribe module cas
        #
        mysql -e "DELETE FROM lcs_db.applis WHERE name = '$MODULE';" > /dev/null 2>&1
        #
        # Stop CAS service
        #
        if [ -e /var/run/rubycas-lcs/casserver.pid ]; then
        	PIDPROCESS=`cat $PIDFILE`
        	kill -9 $PIDPROCESS            
        fi
        #
        # Desactivate lcs log2cas
        #
        /usr/bin/mysql -e "UPDATE lcs_db.params SET value='0' WHERE name='lcs_cas';"
        #
        # Remove rc.d system V rubycas-lcs
        #
        rm -f /etc/init.d/rubycas-lcs
        update-rc.d rubycas-lcs remove
		#
		# Uninstall gems rubycas-server and dependencies
		#
		gem uninstall -a -I -x  rubycas-server
		gem uninstall  -a -I -x mysql
		gem uninstall  -a -I -x ruby-net-ldap
		gem uninstall  -a -I -x picnic
		gem uninstall  -a -I -x markaby
		gem uninstall  -a -I -x activerecord
		gem uninstall  -a -I -x activesupport
		gem uninstall  -a -I -x rack
		gem uninstall  -a -I -x locale
		gem uninstall  -a -I -x gettext
		gem uninstall  -a -I -x builder
        ;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

exit 0
