#! /bin/sh
# postrm script for LCS CAS

set -e

MODULE="cas"

case "$1" in
	purge|remove)
        #
        # unsubscribe module cas
        #
        mysql -e "DELETE FROM lcs_db.applis WHERE name = '$MODULE';" > /dev/null 2>&1
        #
        # Stop CAS service
        #
        if [ -e /etc/init.d/rubycas-lcs ] && [ -e /var/run/rubycas-lcs/casserver.pid ]; then
            invoke-rc.d rubycas-lcs stop
        fi
        #
        # Desactivate lcs log2cas
        #
        /usr/bin/mysql -e "UPDATE lcs_db.params SET value='0' WHERE name='lcs_cas';"
        #
        # Remove rc.d system V rubycas-lcs
        #
        rm -f /etc/init.d/rubycas-lcs
        update-rc.d rubycas-lcs remove
		#
		# Uninstall gems rubycas-server and dependencies
		#
		/usr/sbin/lcs-cas-uninstall.sh
        ;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

exit 0
