#!bin/bash
## Apache 2
 mv /etc/apache2/lcs-main/95_assr.conf.disable /etc/apache2/lcs-main/95_assr.conf
 /etc/init.d/apache2 reload

## Bind
 
cp /etc/bind/localnet.db /etc/bind/localnet.db.noassr
oldserial=`cat /etc/bind/localnet.db | grep -i serial`
newserial=`date +"%Y%m%d"`"01; serial"
sed -i'' 's/"$oldserial"/"$newserial"/g' /etc/bind/localnet.db
echo "assr            IN      CNAME   lcs">>/etc/bind/localnet.db

/etc/init.d/bind9 reload
