#!/bin/bash

# revoke a certificate, regenerate CRL,
# and verify revocation

export KEY_DIR=/usr/share/lcs/openvpn/keys
export KEY_COUNTRY=$COUNTRYNAME
export KEY_PROVINCE=$PROVINCENAME
export KEY_CITY=$LOCALITYNAME
export KEY_ORG=$ORGANIZATIONNAME
export KEY_EMAIL=admin@$DOMAIN
export KEY_SIZE=1024
export KEY_CONFIG=/etc/lcs/openvpn/openssl.cnf
export KEY_COMMONNAME=$1

CRL=crl.pem
RT=revoke-test.pem

if test $# -ne 1; then
	echo "usage: lcs-openvpn-revoke <name>";
	exit 1
fi
             
if test $KEY_DIR; then
       cd $KEY_DIR
       rm -f $RT
             
      # revoke key and generate a new CRL
      openssl ca -revoke $1.crt -config $KEY_CONFIG
                                          
      # generate a new CRL
      openssl ca -gencrl -out $CRL -config $KEY_CONFIG
      cat ca.crt $CRL >$RT
                              
      # verify the revocation
      openssl verify -CAfile $RT -crl_check $1.crt
else
      echo you must define KEY_DIR
fi
                                                                                          
