#!/bin/sh


##
# Configuration inital de OpenVPN
# Projet LCS 2
# /usr/sbin/lcs-openvpn-config
# auteur : Simon CAVEY 
# creation : 04/01/2009 modification
##
set -e
# lecture d'un parametre lcs dans lcs_db.params
get_lcsdb_params() {
mysqlpass=`cat /var/www/lcs/includes/config.inc.php | grep PASSAUTH= | cut -d = -f 2 | cut -d \" -f 2`
PARAMS=`echo  "SELECT value FROM params WHERE name='$1'"| mysql -u lcsmgr -p$mysqlpass lcs_db -N`
echo "$PARAMS"
}

configure() {
	FQN=`hostname -f`
	LCSIP=$(get_lcsdb_params lcsip)
	VPNNET=$(get_lcsdb_params vpnnet)
	VPNPORT=$(get_lcsdb_params vpnport)
	DOMAIN=$(get_lcsdb_params domain)
	VLANSC=$(get_lcsdb_params vlansc)
	VLANADMINISTRATIF=$(get_lcsdb_params vlanadmin)
	VLANPEDA1=$(get_lcsdb_params vlanpeda1)
	VLANPEDA2=$(get_lcsdb_params vlanpeda2)
	VLANPEDA3=$(get_lcsdb_params vlanpeda3)
	VLANPEDA4=$(get_lcsdb_params vlanpeda4)
	CONTRY=$(get_lcsdb_params country)
	PROVINCE=$(get_lcsdb_params province)
	LOCALITY=$(get_lcsdb_params locality)
	ORG=$(get_lcsdb_params organization)
	ORGUNIT=$(get_lcsdb_params $(get_lcsdb_params organizationalunit)
}

case "$1" in
    possible)
	if pgrep -u mysql mysqld >/dev/null; then
	    exit 0
	else
	    exit 1
	fi
    ;;
    needed)
	exit 0
    ;;
    configure)
	configure
    ;;
    "")
	if $0 possible && $0 needed; then
	    $0 configure
	fi
    ;;
esac

