#!/bin/bash
if [ ! -e ../Includes/config.inc.php ]; then
    pass=`pwgen -1`
    pass2=`pwgen -1`
    echo "Patch du fichier de la base MySQL..."
    cp -a install_mysql.sql install_mysql.sq
    cat install_mysql.sq | sed -e "s/#PASS#/$pass/g" > install_mysql.sql
    echo "Patch du fichier config.inc.php..."
    cat ../Includes/config.inc.ph | sed -e "s/#PASS#/$pass/g" > ../Includes/config.inc.ph1
    cat ../Includes/config.inc.ph1 | sed -e "s/#PASS2#/$pass2/g" > ../Includes/config.inc.php
    chown www-data:www-data ../Includes/config.inc.php install_mysql.sql
    rm ../Includes/config.inc.ph	../Includes/config.inc.ph1
    
    
fi
if [ ! -e ../Includes/creneau.inc.php ]; then
	echo "Patch du fichier creneau.inc"
    mv ../Includes/creneau.inc.ph ../Includes/creneau.inc.php
	chown www-data:www-data ../Includes/creneau.inc.php
fi

if [ ! -e ../Includes/data.inc.php ]; then
	echo "Patch du fichier data.inc"
    mv ../Includes/data.inc.ph ../Includes/data.inc.php
	chown www-data:www-data ../Includes/data.inc.php
fi


#
# Recuperation du BASEDN de l'annuaire
#
BASEDN=`mysql -se "select value from lcs_db.params  where name='ldap_base_dn'"`
#
# Patch des fichiers ldif d'installation et desinstallation initiale
#
echo "Patch des fichiers ldif"
mv install_ldap.ldif install_ldap.ldif.in
cat install_ldap.ldif.in | sed -e "s/#BASEDN#/$BASEDN/g" > install_ldap.ldif
rm install_ldap.ldif.in
mv desinstall_ldap.ldif desinstall_ldap.ldif.in
cat desinstall_ldap.ldif.in | sed -e "s/#BASEDN#/$BASEDN/g" > desinstall_ldap.ldif
chown www-data:www-data *.ldif
chmod 600 *.ldif 
rm desinstall_ldap.ldif.in
#
# Patch des fichiers Maj/ldap.x
#
echo "patch des fichiers de maj"
for dir in Maj/ldap.*; do
   if [ -e $dir ]; then
      mv $dir $dir.in
      cat $dir.in | sed -e "s/#BASEDN#/$BASEDN/g" > $dir
      chown www-data:www-data $dir 
      chmod 600 $dir
      rm $dir.in
   fi
done
#
# Fin
#
echo "Fin des patches..."


#
#Installation du paquet phpx-gd
#
#cas d'un sarge et php4
if [  -e /etc/php4  -a ! -e /etc/php5 ] ; then
vartest=`dpkg -l php4-gd | grep ii | wc -l`
if [ $vartest -eq 0 ]; then
	echo "Installation du paquet php4-gd"
	apt-get -qq  update
	apt-get -y -qq install php4-gd
	vartest=`dpkg -l php4-gd | grep ii | wc -l`
	if [ $vartest -eq 0 ]; then
		echo "Une ERREUR est survenue lors de l\'installation du paquet php4-gd" 
		else echo "Le paquet php4-gd a été installé"
	fi



#
# Redémarrage apache
#
echo "Apache sera redémarré dans une minute"
at now +1 minutes < /usr/share/lcs/Plugins/Cdt/Admin/jobat
fi

fi

#cas d'un etch et php5 (normalement le paquet est déjà installé sur un lcs etch) 
if [  -e /etc/php5 ] ; then
vartest=`dpkg -l php5-gd | grep ii | wc -l`
if [ $vartest -eq 0 ]; then
	echo "Installation du paquet php5-gd"
	apt-get -qq  update
	apt-get --force-yes -qq install php5-gd
	vartest=`dpkg -l php5-gd | grep ii | wc -l`
	if [ $vartest -eq 0 ]; then
		echo "Une ERREUR est survenue lors de l\'installation du paquet php5-gd" 
		else echo "Le paquet php5-gd a été installé"
	fi
#
# Redémarrage apache2
#
echo "Apache2 sera redémarré dans une minute"
at now +1 minutes < /usr/share/lcs/Plugins/Cdt/Admin/jobat2
fi

fi
	