#! /bin/sh

set -e

# Read lcs parametre in lcs_db.params
get_lcsdb_params() {
    MYSQLPASS=`cat /var/www/lcs/includes/config.inc.php | grep PASSAUTH= | cut -d = -f 2 | cut -d \" -f 2`
    PARAMS=`echo  "SELECT value FROM params WHERE name='$1'"| mysql -u lcsmgr -p$MYSQLPASS lcs_db -N`
    echo "$PARAMS"
}
		
configure() {
	CONFIG_PATH="/var/lib/lcs/roundcube/Config_rc"
	CONFIGRC_PATH="/usr/share/lcs/roundcube/config"
	CONFIGRCPLUG_PATH="/usr/share/lcs/roundcube/plugins"
	MYSQLDUMP="/var/lib/lcs/roundcube/Sql"
    MYSQLPASS=`cat /var/www/lcs/includes/config.inc.php | grep PASSAUTH= | cut -d = -f 2 | cut -d \" -f 2`
    # Subscribe Module lcs-roundcube dans lcs_db.params
    ROUNDCUBE=`echo "SELECT id from lcs_db.applis WHERE name='webmail';"| mysql -u lcsmgr -p$MYSQLPASS lcs_db -N`
    VER=$(dpkg-query -f '${Version}' -W lcs-roundcube)
    if [ -z "$ROUNDCUBE" ]; then
	echo "INSERT INTO lcs_db.applis (id, name, value, descr, num_maj, version, chemin, type) VALUES ('', 'webmail', '1', 'webmail squirrelmail', '0', '$VER', '/usr/share/squirrelmail', 'S');"| mysql -u lcsmgr -p$MYSQLPASS lcs_db 
    else
        echo "UPDATE lcs_db.applis SET version='$VER' WHERE name='webmail';" | mysql -u lcsmgr -p$MYSQLPASS lcs_db 
    fi
    # Create mysql base for roundcube
	if [  ! -d /var/lib/mysql/roundcube ]; then
		mysqladmin create roundcube
		mysql -se "grant all privileges on roundcube.* to lcsmgr@localhost;"
		mysql roundcube < $MYSQLDUMP/mysql.initial.sql
	fi
	# Make roundcube config
	cp $CONFIG_PATH/db.inc.php.dist $CONFIGRC_PATH/db.inc.php
	sed -i "s|#PASS#|"$MYSQLPASS"|g" $CONFIGRC_PATH/db.inc.php
	CRYPT24=`pwgen 24 1`
	cp $CONFIG_PATH/main.inc.php.dist $CONFIGRC_PATH/main.inc.php
	sed -i "s|#CRYPT24#|"$CRYPT24"|g" $CONFIGRC_PATH/main.inc.php
	# Make lcs_authentication config
	cp $CONFIG_PATH/config_auth_lcs.inc.php.dist $CONFIGRCPLUG_PATH/lcs_authentication/config_auth_lcs.inc.php
	sed -i "s|#PASS#|"$MYSQLPASS"|g" $CONFIGRCPLUG_PATH/lcs_authentication/config_auth_lcs.inc.php
    # Fix rights on module
    /var/lib/lcs/roundcube/Scripts/fixrights.sh
    # Reload apache2
    invoke-rc.d apache2 reload
}

case "$1" in
    possible)
        if pgrep -u mysql mysqld >/dev/null; then
            exit 0
        else
            exit 1
        fi
    ;;
    needed)
        exit 0
    ;;
    configure)
        configure
    ;;
    "")
        if $0 possible && $0 needed; then
            $0 configure
        fi
    ;;
esac

