#! /bin/sh

# lcs-roundcube-update

set -e

MYSQLDUMP="/var/lib/lcs/roundcube/Sql"
CONFIG_PATH="/var/lib/lcs/roundcube/Config_rc"
CONFIGRC_PATH="/usr/share/lcs/roundcube/config"
CONFIGRC_TMP="config.inc.php.dist"
CONFIGRC_FILE="config.inc.php"
CONFIGRCPLUG_PATH="/usr/share/lcs/roundcube/plugins"
MYSQLPASS=`cat /var/www/lcs/includes/config.inc.php | grep PASSAUTH= | cut -d = -f 2 | cut -d \" -f 2`
# Read lcs parametre in lcs_db.params
get_lcsdb_params() {
    MYSQLPASS=`cat /var/www/lcs/includes/config.inc.php | grep PASSAUTH= | cut -d = -f 2 | cut -d \" -f 2`
    PARAMS=`echo  "SELECT value FROM params WHERE name='$1'"| mysql -u lcsmgr -p$MYSQLPASS lcs_db -N`
    echo "$PARAMS"
}
#
# Update version
#
VER=$(dpkg-query -f '${Version}' -W lcs-roundcube)
echo "UPDATE lcs_db.applis SET version='$VER' WHERE name='roundcube';" | mysql -u lcsmgr -p$MYSQLPASS lcs_db 
#
# Update database
#
# 2011121400 0.8.1
# 2012080700 0.9b
# 201311700 Err màj package 2.4.10~8
# 2014042900 1.0.1

if ! mysql -se "show tables from roundcube;" | grep system ; then
	echo "Add system table 0.8.1 2011121400 "
	mysql roundcube < $MYSQLDUMP/system.sql
fi

RC_VER=`mysql -se " select value from roundcube.system where name='roundcube-version';"`

if [ "$RC_VER" = "2011121400" ]; then
	echo "update roundcube database 0.8.1 -> 0.9.4"
	mysql roundcube < $MYSQLDUMP/2012080700.sql
	mysql roundcube < $MYSQLDUMP/2013011000.sql
	mysql roundcube < $MYSQLDUMP/updateversion094.sql	        
fi

RC_VER=`mysql -se " select value from roundcube.system where name='roundcube-version';"`
	
if [ "$RC_VER" = "2012080700" ] || [ "$RC_VER" = "2013011700" ]; then
	echo "update roundcube database 0.9.4 -> 1.0.1" 
	mysql roundcube < $MYSQLDUMP/2013052500.sql	       
	mysql roundcube < $MYSQLDUMP/2013061000.sql	
	mysql roundcube < $MYSQLDUMP/2014042900.sql
	mysql roundcube < $MYSQLDUMP/updateversion101.sql	
	# Reload apache2
	invoke-rc.d apache2 reload	
fi

# Update config files
#
# Make roundcube config
#
cp $CONFIG_PATH/$CONFIGRC_TMP $CONFIGRC_PATH/$CONFIGRC_FILE	
sed -i "s|#PASS#|"$MYSQLPASS"|g" $CONFIGRC_PATH/$CONFIGRC_FILE
CRYPT24=`pwgen 24 1`
sed -i "s|#CRYPT24#|"$CRYPT24"|g" $CONFIGRC_PATH/$CONFIGRC_FILE
MAILDOMAIN=`hostname -d`
sed -i "s|#MAILDOMAIN#|"$MAILDOMAIN"|g" $CONFIGRC_PATH/$CONFIGRC_FILE
LDAP_SERVER=$(get_lcsdb_params ldap_server)
LDAP_BASE_DN=$(get_lcsdb_params ldap_base_dn)
LDAP_PEOPLE_RDN=$(get_lcsdb_params peopleRdn)	
sed -i "s|#LDAP_SERVER#|"$LDAP_SERVER"|g" $CONFIGRC_PATH/$CONFIGRC_FILE	
sed -i "s|#LDAP_BASE_DN#|"$LDAP_BASE_DN"|g" $CONFIGRC_PATH/$CONFIGRC_FILE
sed -i "s|#LDAP_PEOPLE_RDN#|"$LDAP_PEOPLE_RDN"|g" $CONFIGRC_PATH/$CONFIGRC_FILE
# Config Roundcube authentication mode
AUTH_MOD=$(get_lcsdb_params auth_mod)
if [ ! -z $AUTH_MOD ]; then
	if [ "$AUTH_MOD" = "ENT" ]; then
		MODAUTHENTICATION="cas_authentication"
	else
		MODAUTHENTICATION="lcs_authentication"
	fi
else
		MODAUTHENTICATION="lcs_authentication"
fi
sed -i "s|#MODAUTHENTICATION#|"$MODAUTHENTICATION"|g" $CONFIGRC_PATH/$CONFIGRC_FILE
# Make lcs_authentication config
cp $CONFIG_PATH/config_auth_lcs.inc.php.dist $CONFIGRCPLUG_PATH/lcs_authentication/config_auth_lcs.inc.php
sed -i "s|#PASS#|"$MYSQLPASS"|g" $CONFIGRCPLUG_PATH/lcs_authentication/config_auth_lcs.inc.php
# Make cas_authentication config
HOSTNAME=`hostname -f`
cp $CONFIG_PATH/config_auth_cas.inc.php.dist $CONFIGRCPLUG_PATH/cas_authentication/config.inc.php
sed -i "s|#HOSTNAME#|"$HOSTNAME"|g" $CONFIGRCPLUG_PATH/cas_authentication/config.inc.php
# Clean old config files 
rm -f $CONFIGRC_PATH/db.inc.php  
rm -f $CONFIGRC_PATH/db.inc.php.dist  
rm -f $CONFIGRC_PATH/main.inc.php  
rm -f $CONFIGRC_PATH/main.inc.php.dist
# Fix rights on module
/var/lib/lcs/roundcube/Scripts/fixrights.sh

exit 0