#! /bin/sh
# postinst script for lcs-dns

set -e

# Exit fatal
exit_fatal()
{
	echo "Fatal: $1" >&2
	exit 0
}

# Read params in lcs_db.params
get_lcsdb_params()
{
    PARAMS=`echo  "SELECT value FROM params WHERE name='$1'"| mysql lcs_db -N`
    echo "$PARAMS"
}

# Get lcs-dns package version
VER=$(dpkg-query -f '${Version}' -W lcs-dns)

case "$1" in
    install|configure)
	if [ "$2" = "" ] || [ "$2" = "$VER" ]; then
	   #
	   # only if first configuration
	   #
	   echo "LCS DNS first install"
           if ! lcs-test-mysql; then
                #
                # Read LCS params from /etc/lcs/lcs.conf
                #
                echo "get params from lcs.conf"
                [ ! -e /etc/lcs/lcs.conf ] && exit_fatal "missing /etc/lcs/lcs.conf"
                    . /etc/lcs/lcs.conf
            else
                echo "get params from lcs_db.params"
                DNS_PRIMARY=$(get_lcsdb_params dns1)
                DNS_SECONDARY=$(get_lcsdb_params dns2)
                IPADDR0=$(get_lcsdb_params iplcs)
                HOSTNAME=$(get_lcsdb_params hostname)
                DOMAIN=$(get_lcsdb_params domain)
            fi
	    # dns_reconfigure.sh <DNS_PRIMARY> <DNS_SECONDARY> <IPADDR> <HOSTNAME> <DOMAIN>
            /usr/sbin/dns_reconfigure.sh $DNS_PRIMARY $DNS_SECONDARY $IPADDR0 $HOSTNAME $DOMAIN
	else
            echo "LCS DNS update package"
	fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
exit 0
