#! /bin/sh

set -e

case "$1" in
    purge)
	# Drop credentials files
	rm -rf /var/lib/lcs/zonep

	# Drop manually handled config file
	rm -f /etc/auto.zonep

	# Update sudoers file
	lcs-make-sudoers || true
        ;;

    remove)
	# Drop custom config in autofs
	if [ -e /etc/auto.master ]; then
	    sed -i "/^\/srv\/zone_p / d" /etc/auto.master
	fi
	;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
	;;
esac

#DEBHELPER#

exit 0
