#!/bin/sh
# postinst script 
#
# see: dh_installdeb(1)

set -e

MODULE="Claro"
module=`echo $MODULE | tr [:upper:] [:lower:]`
VER=$(dpkg-query -f '${Version}' -W lcs-$module)
PATHPLUG="/usr/share/lcs/Plugins/$MODULE"
INDICEMAJNBR="6"
DESCRIPT="Plateforme de formation"
CONF="/var/lib/lcs/$MODULE"
LCSAPACH2PATH="/etc/apache2/lcs-main/"
APACHE2CONF=$LCSAPACH2PATH"73_claro_module.conf"

case "$1" in
   install| configure)

CHEMIN=`pwd`
#
# execution du patchconf
#
	if [ -e $PATHPLUG/Admin/patchconf ]; then
	echo "Execution du script patchconf"
	cd $PATHPLUG/Admin
	$PATHPLUG/Admin/patchconf
	else
	echo "Pas de patchconf a executer"
	fi

# test si le plugin est installe
TEST=`mysql -se "SELECT type FROM lcs_db.applis WHERE  name='Claroline';"`

if [ "$2" = "" -o "$2" = "$VER" ] && [ "$TEST" != "P" ]; then

#----------------
#install initiale
#----------------

    #-----------------------------
    #installation de la base mysql
    #-----------------------------

    if [ -e $PATHPLUG/Admin/install_mysql.sql ]; then
    echo "Installation de la base MySQL"
    mysql < $PATHPLUG/Admin/install_mysql.sql
    else
	echo "Pas de base mysql a installer"
	fi

    #-----------------------------
    #Execution du script d'install
    #-----------------------------

    if [ -e $PATHPLUG/Admin/install ]; then
    echo "Execution du script d installation"
    $PATHPLUG/Admin/install
    else
	echo "Pas de script d installation a executer"
	fi


    #-------------------------------
    # Inscription dans applis.lcs_db
    #-------------------------------

    /usr/bin/mysql -e "INSERT INTO lcs_db.applis (id, name, value, descr, num_maj, version, chemin, type) VALUES ('', '$module', '1', '$DESCRIPT', 
'$INDICEMAJNBR', '$VER', '$MODULE', 'N');"

else

#-----------
#Mise a jour
#-----------

    echo "Mise a jour du paquet module LCS $MODULE de $2 vers $VER"

    #-------------------------------------------------------
    # Lecture de l'indice de maj dans la table lcs_db.applis
    #-------------------------------------------------------

    # test si le module  est installe
    TESTMOD=`mysql -se "SELECT type FROM lcs_db.applis WHERE  name='$module';"`
    if [ "$TESTMOD" = "N" ]; then
    REF=`mysql -se "SELECT num_maj FROM lcs_db.applis WHERE  name='$module';"`
    else
    REF=`mysql -se "SELECT num_maj FROM lcs_db.applis WHERE name='Claroline';"`
    fi

    MAJNBR=$REF
    MAJNBR=$((MAJNBR+1))
    if [ ! -e $PATHPLUG/Admin/Maj/maj.$MAJNBR ]; then
	echo "Pas de script de mise a jour a appliquer !"
    else

    #--------------------------------
    #Execution des instructions mysql
    #--------------------------------

    MAJNBR=$REF
    MAJNBR=$((MAJNBR+1))
    if [ -e $PATHPLUG/Admin/Maj/mysql.$MAJNBR ]; then
    echo "Execution des instructions MySQL des mises a jour"

        while [ -e $PATHPLUG/Admin/Maj/mysql.$MAJNBR ]; do
            echo " - Application du script mysql.$MAJNBR"
            mysql < $PATHPLUG/Admin/Maj/mysql.$MAJNBR
            MAJNBR=$((MAJNBR+1))
	done
    fi


    #---------------------
    #Execution des scripts
    #---------------------

    MAJNBR=$REF
    MAJNBR=$((MAJNBR+1))
        while [ -e $PATHPLUG/Admin/Maj/maj.$MAJNBR ]; do
            echo "Application du script Maj$MAJNBR"
            $PATHPLUG/Admin/Maj/maj.$MAJNBR
            MAJNBR=$((MAJNBR+1))
	done

  fi
  # fin de la maj par les scripts mysql,bash

	#---------------------------------
	# Mise a jour du Numero de version
	#---------------------------------


        #
        # Inscription du module dans applis.lcs_db
        #
     	if [ "$TESTMOD" = "N" ]; then
        /usr/bin/mysql -e "UPDATE lcs_db.applis SET num_maj='$INDICEMAJNBR', version='$VER', name='$module', type='N' WHERE name='$module' ;" 
        else
	#cas de migration plugin to module
	/usr/bin/mysql -e "INSERT INTO lcs_db.applis (id, name, value, descr, num_maj, version, chemin, type) VALUES ('', '$module', '1','$DESCRIPT','$INDICEMAJNBR', '$VER', '$MODULE', 'N');"	 #
        #desactivation du plugin
	/usr/bin/mysql -e "UPDATE lcs_db.applis SET value='0' WHERE name='Claroline';"
	#maj de mediacenter
		if [ -e $PATHPLUG/module/INWICAST ]; then
		cp $CONF/mediacenter.tgz $PATHPLUG/module/INWICAST
		cd $PATHPLUG/module/INWICAST
		tar xzf mediacenter.tgz
		rm mediacenter.tgz
		fi
	fi
	# Fin de la mise a jour
        #

fi
	#
	#
	# Configuration apache
	if [ -d $LCSAPACHE2PATH ] && [ ! -e $APACHE2CONF ] ; then
  	cat >$APACHE2CONF <<EOF
<Directory /usr/share/lcs/Plugins/Claro>
AddDefaultCharset UTF-8
</Directory>
EOF
   	/etc/init.d/apache2 reload > /dev/null 2>&1
	fi
	# 
	# 
	echo "Changement des droits sur l'arborescence du module"
	#
	$CONF/Scripts/chown.sh $MODULE
	cd $CHEMIN
	echo "Fin de l'installation"
        cd $PATHPLUG
	rm -rf claroline/install claroline/admin/upgrade/my_upgrade_to_1_9.php claroline/admin/upgrade/my_upgrade_to_1_10.php
;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0


