#! /bin/bash
# preinst script for LCS claro

set -e
case "$1" in
install)
#
#duplication du plugin si migration
#
Test_Plugin=`mysql -se "SELECT type FROM lcs_db.applis WHERE name='Claroline';"` 
Test_Module=`mysql -se "SELECT type FROM lcs_db.applis WHERE name='claro';"` 
if [ "$Test_Module" != "N" ] && [ "$Test_Plugin" = "P" ]; then 
#
echo "La version de la plateforme Claroline actuellement installée (1.8) ne peut pas être mise à jour par ce module "
echo "Vous devez  préalablement installer la version 1.10  de Claroline en installant  le module :"
echo "    lcs-claro 2.4.9 pour squeeze"
echo "    lcs-claro 2.4.8.1 pour lenny (branche XP)" 
exit 1
fi
 ;;
 abort-upgrade)
 ;;
 upgrade)
 ;;
*)
echo "preinst called with unknown argument \`$1'" >&2
exit 1
;;
esac
exit 0



