#!/usr/bin/make -f

all:

install:
	# install conf files
	#install -d $(DESTDIR)/etc/lcs/courier
	#install -m 644 conf/* $(DESTDIR)/etc/lcs/courier/
	
	# install sbin
	install -d $(DESTDIR)/usr/share/lcs/sbin
	install -m 755 sbin/* $(DESTDIR)/usr/share/lcs/sbin

clean:


.PHONY: all install clean


