#! /bin/sh
# postrm script for LCS monlcs

set -e
MODULE="monlcs"
PATHMOD="/var/www/$MODULE"
CONF="/var/lib/lcs/$MODULE"

# lecture d'un parametre lcs dans lcs_db.params
function get_lcsdb_params
{
mysqlpass=`cat /var/www/lcs/includes/config.inc.php | grep PASSAUTH= | cut -d = -f 2 | cut -d \" -f 2`
PARAMS=`echo  "SELECT value FROM params WHERE name='$1'"| mysql -u lcsmgr -p$mysqlpass lcs_db -N`
echo "$PARAMS"
}

case "$1" in
	purge|remove)
        #
        # Acquisition des parametres LCS nécessaires a l'installation
        #
        LDAP_SERVER=$(get_lcsdb_params ldap_server)
        LDAP_BASE_DN=$(get_lcsdb_params ldap_base_dn)
        LDAP_ADMIN_RDN=$(get_lcsdb_params adminRdn)
        LDAP_ADMIN_PW=$(get_lcsdb_params adminPw)
        #
        # Desinscription du module de la table lcs_db.applis
        # 
        /usr/bin/mysql -e "DELETE FROM lcs_db.applis WHERE name = '$MODULE';" > /dev/null 2>&1
        #
        # Suppression de la base de données monlcs_db
        #
        mysql -e "DROP DATABASE IF EXISTS monlcs_db;" > /dev/null 2>&1
        #
        # Suppression des entrées dans mysql db
        #
        mysql -e "DELETE FROM mysql.db WHERE Db = 'monlcs_db';" > /dev/null 2>&1
        #
        # Suppression des entrées dans mysql user
        #
        mysql -e "DELETE FROM mysql.user WHERE user = 'monlcs_user';" > /dev/null 2>&1
        mysqladmin reload > /dev/null 2>&1
        #
        # Positionnement de url_accueil 
        #
        mysql -e "UPDATE lcs_db.applis SET value='/lcs/accueil.php' WHERE name='url_accueil';" > /dev/null 2>&1
        #
        # Suppression du droit monlcs_is_admin
        #
        PRESENT=`ldapsearch -xLLL "cn=monlcs_is_admin" | wc -l`
        if [ "$PRESENT" != "0" ]; then
            ldapdelete -x -w $LDAP_ADMIN_PW -D $LDAP_ADMIN_RDN,$LDAP_BASE_DN -h $LDAP_SERVER "cn=monlcs_is_admin,ou=Rights,$LDAP_BASE_DN" > /dev/null 2>&1
        fi
        # Nettoyage des rep monlcs
        if [ -d  $PATHMOD ];then
            rm -R $PATHMOD > /dev/null 2>&1
        fi
        exit 0
        ;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

exit 0
