#! /bin/sh
# postinst script for LCS monlcs
set -e
MODULE="monlcs"
VER=$(dpkg-query -f '${Version}' -W lcs-$MODULE)
INDICEMAJNBR="0"

CONF="/var/lib/lcs/$MODULE"
PATHMOD="/var/www/$MODULE"
PATHMAJ="/var/lib/lcs/$MODULE"

# lecture d'un parametre lcs dans lcs_db.params
function get_lcsdb_params() {
    mysqlpass=`cat /var/www/lcs/includes/config.inc.php | grep PASSAUTH= | cut -d = -f 2 | cut -d \" -f 2`
    PARAMS=`echo  "SELECT value FROM params WHERE name='$1'"| mysql -u lcsmgr -p$mysqlpass lcs_db -N`
    echo "$PARAMS"
}

PASS=`cat /var/www/lcs/includes/config.inc.php | grep PASSAUTH= | cut -d = -f 2 | cut -d \" -f 2`

if [ "$2" = "" ] || [ "$2" = "$VER" ]; then
    ##
    ## Configuration initiale du module
    ##
    #
    # Acquisition des parametres LCS nécessaires a l'installation
    #
    LDAP_SERVER=$(get_lcsdb_params ldap_server)
    LDAP_BASE_DN=$(get_lcsdb_params ldap_base_dn)
    LDAP_ADMIN_RDN=$(get_lcsdb_params adminRdn)
    LDAP_ADMIN_PW=$(get_lcsdb_params adminPw)
    #
    # base de données monlcs_db
    #
    echo "Mise en place base de données monlcs :"
    mysql -e "DROP DATABASE IF EXISTS monlcs_db;" > /dev/null 2>&1
    mysql -e "CREATE DATABASE monlcs_db;" > /dev/null 2>&1	
    mysql -e "USE monlcs_db;" > /dev/null 2>&1
    mysql -u root -h localhost -D monlcs_db < $CONF/Sql/monlcs.sql
    mysql -e "GRANT ALL PRIVILEGES ON monlcs_db.* TO admin@localhost;" > /dev/null 2>&1
    mysql -e "GRANT ALL PRIVILEGES ON monlcs_db.* TO monlcs_user@localhost IDENTIFIED BY '$PASS';" > /dev/null 2>&1
    #
    # Positionnement de url_accueil 
    #
    mysql -e " UPDATE lcs_db.applis SET value='/monlcs/' WHERE name='url_accueil';" > /dev/null 2>&1
    #
    # Droit monlcs_is_admin
    #
    PRESENT=`ldapsearch -xLLL "cn=monlcs_is_admin" | wc -l`
    if [ "$PRESENT" == "0" ]; then
        echo "Mise en place du droit monlcs_is_admin dans l'annuaire"
    	cp -a $CONF/Ldif/monlcs.ldif.in $CONF/Ldif/monlcs.ldif
    	sed -i "s/#BASEDN#/$LDAP_BASE_DN/g" $CONF/Ldif/monlcs.ldif
        ldapadd -x -w $LDAP_ADMIN_PW -D $LDAP_ADMIN_RDN,$LDAP_BASE_DN -h $LDAP_SERVER -f $CONF/Ldif/monlcs.ldif
        rm $CONF/Ldif/monlcs.ldif
    else
	echo "monlcs_is_admin est deja présent"
    fi
    #
    # Extension gd sous sarge
    #
    VERSION=`cat /etc/debian_version`
    if [ $VERSION = "3.1" ];then
        if [ -d /etc/php4/apache/php.ini ];then
            GD=`cat /etc/php4/apache/php.ini | grep "^extension=gd.so"`
            if [ -z $GD ]; then
                echo "extension=gd.so" >> /etc/php4/apache/php.ini
            fi
            /usr/sbin/apachectl graceful > /dev/null 2>&1
        fi
    fi
    #
    # Inscription du module et de l'indice numero de version dans applis.lcs_db
    #
    /usr/bin/mysql -e "INSERT INTO lcs_db.applis (id, name, value, descr, num_maj, version, chemin, type) VALUES ('', '$MODULE', '1', 'Mon LCS portail pédagogique collaboratif web 2.0', '$INDICEMAJNBR', '$VER', '$PATHMOD', 'S');"

else
    ##
    ## Mise à jour du paquet
    ##
    echo "Mise à jour du paquet module LCS $MODULE de $2 vers $VER"
    #
    # Lecture de l'indice de maj dans la table lcs_db.applis
    #
    MAJNBR=`mysql -se "SELECT num_maj FROM lcs_db.applis WHERE name='$MODULE';"`
    let MAJNBR+=1
    if [ ! -e $CONF/Maj/maj$MAJNBR.sh ]; then
	echo "Pas de script de mise à jour à appliquer !"
    else
        while [ -e $CONF/Maj/maj$MAJNBR.sh ]; do
            echo "Application du script Maj$MAJNBR"
            $CONF/Maj/maj$MAJNBR.sh
            let MAJNBR+=1
	done
        #
        # Fin de la mise à jour
        #
	echo "Application des maj terminée."
    fi
        #
        # Mise à jour de l'indice de Maj
        #
        /usr/bin/mysql -e "UPDATE lcs_db.applis SET num_maj='$INDICEMAJNBR', version='$VER' WHERE name='$MODULE';"

fi
#
# Actions communes à une installation initiale ou à une mise à jour.
#
#
# Mise ou Remise en place du fichier de configuration monlcs
#
cp $CONF/Mod/Config/config.inc.ph $PATHMOD/includes/config.inc.php
sed -i "s/#PASS#/$PASS/g" $PATHMOD/includes/config.inc.php
#
# Changement des droits sur l'arborescence du module
#
echo "Fixation des droits sur l'arborescence du module : $MODULE"
chown -R www-data:www-data $PATHMOD
chown -R www-data:www-data $CONF

exit 0


