#! /bin/sh
# postrm script for LCS web

set -e
case "$1" in
	purge|remove)
			# Drop directives for lcs-web
         rm -f /etc/apache2/lcs-main/55_lcs.conf
         rm -f /etc/apache2/lcs-main/15_files.conf
         invoke-rc.d apache2 force-reload
         /usr/sbin/lcs-make-sudoers
         # rm divert
        if [ "$1" = remove ]; then
    		rm -f /etc/apache2/mods-enabled/php5.conf
    		dpkg-divert --package lcs-web \
        		--rename --remove /etc/apache2/mods-enabled/php5.conf              
        ;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

#DEBHELPER#

exit 0
