#! /bin/sh
# postinst script for LCS web
set -e

case "$1" in
	install|configure)
            #
            # only if first configuration
            #
	    if [ "$2" = "" ]; then
	       . /usr/share/slis/slis-common.sh
	       handle_initial_config lcs-web-config 60
            fi
            # 	   
            # Restore .htpasswd if exist
            #
            if [ -e /var/lib/lcs/tmp/lcswebsetupacces ]; then
                mv /var/lib/lcs/tmp/lcswebsetupacces /var/www/setup/.htpasswd
            # ReGenerate .htpasswd if not exist
            elif [ ! -e /var/www/setup/.htpasswd ]; then
                LOCAL_ADMIN_PW=`pwgen -1 -s 8`
                /usr/bin/htpasswd -bc /var/www/setup/.htpasswd admin $LOCAL_ADMIN_PW
            fi
            #
            # Restore public and private keys
            #
            if [ -e /var/lib/lcs/tmp/public_key.js ]; then
                mv /var/lib/lcs/tmp/public_key.js /var/www/lcs/public_key.js
                mv /var/lib/lcs/tmp/privateKey.py /usr/share/lcs/privatekey/privateKey.py
                rm -f /var/lib/lcs/tmp
            fi
            #
            # Fix rights on lcs-web tree
            #
            /usr/sbin/lcs-web-fixrights
            #
            # Update sudoers
            # 
            /usr/sbin/lcs-make-sudoers
    	;;

    	abort-upgrade|abort-remove|abort-deconfigure)
    	;;

    	*)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    	;;
esac

#DEBHELPER#

exit 0
