#!/bin/bash
echo "Script de desinstallation du plugin gepi";
if [  -e /etc/apache2/lcs-main/71_gepi.conf ]; then
rm -f  /etc/apache2/lcs-main/71_gepi.conf
# Redemarrage apache2
#
echo "Apache2 sera redemarre dans une minute"
at now +1 minutes < /usr/share/lcs/Plugins/Gepi/Admin/jobat2
fi
