#!/bin/bash
echo "Script de desinstallation du plugin gepi";
#cas d'un sarge et php4 
if [  -e /etc/php4 ] ; then
#
echo "Effacement de la section apache gepi";
        #
        # Suppression section gepiplug
        #
        mv /etc/lcs/apache.conf /tmp/apache.conf
        test=true
        share=false
        cat /tmp/apache.conf | while ($test)
        do
            read ligne || test=false
            if [ $test = false ]; then
                exit 0;
            fi
            if [ "$ligne" = "# Debut section gepi plugin" ]; then
                share=true
            fi
            if [ $share = false ]; then
                echo "$ligne" >>  /etc/lcs/apache.conf
            fi
            if [ "$ligne" = "# Fin section gepi plugin" ]; then
                share=false
            fi
        done
        rm /tmp/apache.conf 
#
# Redémarrage apache
#
at now +1 minutes < /usr/share/lcs/Plugins/Gepi/Admin/jobat
fi

#cas d'un etch et php5 
if [  -e /etc/php5 ] ; then
#
rm -f  /etc/apache2/lcs-main/71_gepi.conf
# Redémarrage apache2
#
echo "Apache2 sera redémarré dans une minute"
at now +1 minutes < /usr/share/lcs/Plugins/Gepi/Admin/jobat2
fi
