#! /bin/sh
set -e

MODULE="Ggt"
module="ggt"
case "$1" in
    purge|remove)

        #
        # Suppression de la base de donnees 
        #
	mysql -e "DROP DATABASE IF EXISTS ggt_plug;" 
	mysql -e "DELETE FROM mysql.user WHERE User = 'ggt_user' AND Host = 'localhost';" 
	mysql -e "DELETE FROM mysql.db WHERE User = 'ggt_user' AND Host = 'localhost';" 
	mysql -e "DELETE FROM mysql.tables_priv WHERE User = 'ggt_user' AND Host = 'localhost';"
	mysql -e "DELETE FROM mysql.columns_priv WHERE User = 'ggt_user' AND Host = 'localhost';"
	mysql -e "FLUSH PRIVILEGES;" 
        #
        # Desinscription du module de la table lcs_db.applis
        #
        mysql -e "DELETE FROM lcs_db.applis WHERE name = '$module';"
        #
        # Nettoyage des repertoires
        # 
        if [ -e /usr/share/lcs/$MODULE ]; then
	echo "Suppression du repertoire /usr/share/lcs/$MODULE"   
	rm -R /usr/share/lcs/$MODULE
        fi
        if [ -e /var/lib/lcs/$MODULE ]; then
	echo "Suppression du repertoire /var/lib/lcs/$MODULE"   
	rm -R /var/lib/lcs/$MODULE
        fi
        exit 0
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

exit 0

