#! /bin/sh

set -e

# lecture d'un parametre lcs dans lcs_db.params
get_lcsdb_params() {
mysqlpass=`cat /var/www/lcs/includes/config.inc.php | grep PASSAUTH= | cut -d = -f 2 | cut -d \" -f 2`
PARAMS=`echo  "SELECT value FROM params WHERE name='$1'"| mysql -u lcsmgr -p$mysqlpass lcs_db -N`
echo "$PARAMS"
}

configure() {
    LDAP_SERVER=$(get_lcsdb_params ldap_server)
    LDAP_BASE_DN=$(get_lcsdb_params ldap_base_dn)
    LDAP_ADMIN_RDN=$(get_lcsdb_params adminRdn)
    LDAP_ADMIN_PW=$(get_lcsdb_params adminPw)
    # imap_reconfigure.sh 
    /usr/share/lcs/scripts/imap_reconfigure.sh $LDAP_SERVER $LDAP_BASE_DN $LDAP_ADMIN_RDN $LDAP_ADMIN_PW
    #
    # Add link mailing list in 50services
    #
    if [ -e /var/www/lcs/includes/menu.d/50services.inc ]; then
        mv /var/www/lcs/includes/menu.d/50services.inc /tmp/50services.inc
        if [ `grep '\"/Admin/listesdiff.php\",\"lcs_is_admin\",' /tmp/50services.inc | wc -l` = "1" ]; then
            sed /tmp/50services.inc -e "s/.*listesdiff.php.*/\t\t\"Listes de diffusion\",\"\/Admin\/listesdiff.php\",\"lcs_is_admin\",/" > /var/www/lcs/includes/menu.d/50services.inc
        else
            sed /tmp/50services.inc -e "s/.*listesdiff.php.*/\t\t\"Listes de diffusion\",\"\/Admin\/listesdiff.php\",\"lcs_is_admin\"/" > /var/www/lcs/includes/menu.d/50services.inc
        fi
        rm -f /tmp/50services.inc
    fi
}

case "$1" in
    possible)
        if pgrep -u mysql mysqld >/dev/null; then
            exit 0
        else
            exit 1
        fi
    ;;
    needed)
        exit 0
    ;;
    configure)
        configure
    ;;
    "")
        if $0 possible && $0 needed; then
            $0 configure
        fi
    ;;
esac

