#!/bin/sh
set -e

VER=$(dpkg-query -f '${Version}' -W lcs-smbwebclient)
MODULE="smbwebclient"
VERAPPLI="2.9"
INDICEMAJNR="1"

CONF="/var/lib/lcs/$MODULE"
PATHMOD="/usr/share/lcs/$MODULE"
APACHECONF="/etc/lcs/apache.conf"
APACHE2CONF="/etc/apache2/lcs-main/71_smbwebclient.conf"

if [ "$2" = "" ] || [ "$2" = "$VER" ]; then
    #
    # Inscription du module dans lcs_db.applis
    #
    /usr/bin/mysql -e "INSERT INTO lcs_db.applis (id, name, value, descr, num_maj, version, chemin, type) VALUES ('', '$MODULE', '1', 'Client web samba pour acces au Se3 depuis le LCS', '$INDICEMAJNBR', '$VER', '$PATHMOD', 'M');"
    #
    # Inscription du params shareview dans lcs_db.params
    #
    /usr/bin/mysql -e "INSERT INTO lcs_db.params VALUES (NULL, 'shareview', 'Docs/Classes/Progs', '0', 'Partages Visibles avec smbwebclient', '1');"
else
    echo "Mise à jour du paquet module LCS $MODULE de $2 vers $VER"
    #
    # Lecture de l'indice de maj dans la table lcs_db.applis
    #
    MAJNBR=`mysql -se "SELECT num_maj FROM lcs_db.applis WHERE name='$MODULE';"`
    let MAJNBR+=1
    if [ ! -e $CONF/Maj/maj$MAJNBR.sh ]; then
	echo "Pas de script de mise à jour à appliquer !"
    else
        while [ -e $CONF/Maj/maj$MAJNBR.sh ]; do
            echo "Application du script Maj$MAJNBR"
            $CONF/Maj/maj$MAJNBR.sh
            let MAJNBR+=1
	done
        #
        # Fin de la mise à jour
        #
	echo "Terminé."
    fi
    #
    # Inscription du module dans applis.lcs_db
    #
    /usr/bin/mysql -e "UPDATE lcs_db.applis SET num_maj='$INDICEMAJNBR', version='$VER' WHERE name='$MODULE';" 

fi
#
# Changement des droits sur l'arborescence du module
#
echo "Fixation des droits sur l'arborescence du module : $MODULE"
$CONF/Scripts/chown.sh $MODULE

# cas de l'ancienne conf apache
if [ -e $APACHECONF ]; then
  if [ `grep -c "Alias /$MODULE/ /usr/share/lcs/$MODULE/" $APACHECONF` = 0 ]; then
    #
    # Ajout de l'alias
    #
    echo "Mise en place de l'alias $MODULE"
    echo "Alias /$MODULE/ /usr/share/lcs/$MODULE/" >> $APACHECONF
    if [ -e /etc/init.d/apache2 ]; then
        /etc/init.d/apache2 reload > /dev/null 2>&1
    else
        /etc/init.d/apache reload > /dev/null 2>&1
    fi
  fi
fi
# cas de la nouvelle configuration apache
if [ ! -e $APACHE2CONF ]; then
  cat >$APACHE2CONF <<EOF
Alias /$MODULE/ /usr/share/lcs/$MODULE/
EOF
  /etc/init.d/apache2 reload > /dev/null 2>&1
fi
#
# Mise en place du lien symbolique vers la documentation
#
if [ ! -e /usr/share/doc/lcs-$MODULE ]; then
    ln -s /usr/share/doc/lcs/$MODULE /usr/share/doc/lcs-$MODULE
fi
#
# Mise en place de samba.conf
#
if [ -e /etc/samba/smb.conf ]; then
    cp $CONF/Mod/samba.conf.in /etc/samba/smb.conf
fi

exit 0