#! /bin/sh
# postinst script for LCS imap
set -e

case "$1" in
	configure)
            # only if first configuration
	    if [ "$2" = "" ]; then
		. /usr/share/slis/slis-common.sh
		handle_initial_config lcs-imap-config 90
	    elif dpkg --compare-versions $2 lt 2.5~; then
		sed -i -e "s/^# LDAP_AUTHBIND.*/LDAP_AUTHBIND 1/" /etc/courier/authldaprc
		invoke-rc.d courier-authdaemon restart || true
	    fi
    	;;

    	abort-upgrade|abort-remove|abort-deconfigure)
    	;;

    	*)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    	;;
esac

#DEBHELPER#

exit 0
