#! /bin/sh
# postinst script for LCS imap
set -e

case "$1" in
	install|configure)
           # only if first configuration
	   if [ "$2" = "" ]; then
	       . /usr/share/slis/slis-common.sh
	       handle_initial_config lcs-imap-config 90
	   fi
            #
            # Add link mailing list in 50services
            #
            mv /var/www/lcs/includes/menu.d/50services.inc /tmp/50services.inc
            if [ `grep '\"/Admin/listesdiff.php\",\"lcs_is_admin\",' /tmp/50services.inc | wc -l` = "1" ]; then
                sed /tmp/50services.inc -e "s/.*listesdiff.php.*/\t\t\"Listes de diffusion\",\"\/Admin\/listesdiff.php\",\"lcs_is_admin\",/" > /var/www/lcs/includes/menu.d/50services.inc
            else
                sed /tmp/50services.inc -e "s/.*listesdiff.php.*/\t\t\"Listes de diffusion\",\"\/Admin\/listesdiff.php\",\"lcs_is_admin\"/" > /var/www/lcs/includes/menu.d/50services.inc
            fi
            rm -f /tmp/50services.inc
    	;;

    	abort-upgrade|abort-remove|abort-deconfigure)
    	;;

    	*)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    	;;
esac

#DEBHELPER#

exit 0
