DROP TABLE IF EXISTS sacoche_parametre;

CREATE TABLE sacoche_parametre (
	parametre_nom    VARCHAR(50)  COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
	parametre_valeur VARCHAR(150) COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
	PRIMARY KEY (parametre_nom)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE sacoche_parametre DISABLE KEYS;

INSERT INTO sacoche_parametre VALUES 
( "version_base"                                  , "" ),
( "sesamath_id"                                   , "0" ),
( "sesamath_uai"                                  , "" ),
( "sesamath_type_nom"                             , "" ),
( "sesamath_key"                                  , "" ),
( "webmestre_uai"                                 , "" ),
( "webmestre_denomination"                        , "" ),
( "etablissement_denomination"                    , "" ),
( "etablissement_adresse1"                        , "" ),
( "etablissement_adresse2"                        , "" ),
( "etablissement_adresse3"                        , "" ),
( "etablissement_telephone"                       , "" ),
( "etablissement_fax"                             , "" ),
( "etablissement_courriel"                        , "" ),
( "mois_bascule_annee_scolaire"                   , "8" ),
( "connexion_mode"                                , "normal" ),
( "connexion_nom"                                 , "sacoche" ),
( "modele_directeur"                              , "ppp.nnnnnnnn" ),
( "modele_professeur"                             , "ppp.nnnnnnnn" ),
( "modele_eleve"                                  , "ppp.nnnnnnnn" ),
( "modele_parent"                                 , "ppp.nnnnnnnn" ),
( "mdp_longueur_mini"                             , "6" ),
( "droit_eleve_demandes"                          , "0" ),
( "droit_modifier_mdp"                            , "directeur,professeur,parent,eleve" ),
( "droit_validation_entree"                       , "directeur,professeur" ),
( "droit_validation_pilier"                       , "directeur,profprincipal" ),
( "droit_annulation_pilier"                       , "directeur,aucunprof" ),
( "droit_gerer_referentiel"                       , "profcoordonnateur" ),
( "droit_gerer_ressource"                         , "professeur" ),
( "droit_voir_referentiels"                       , "directeur,professeur,parent,eleve" ),
( "droit_voir_grilles_items"                      , "directeur,professeur,parent,eleve" ),
( "droit_voir_score_bilan"                        , "directeur,professeur,parent,eleve" ),
( "droit_voir_algorithme"                         , "directeur,professeur,parent,eleve" ),
( "droit_bilan_moyenne_score"                     , "parent,eleve" ),
( "droit_bilan_pourcentage_acquis"                , "parent,eleve" ),
( "droit_bilan_note_sur_vingt"                    , "" ),
( "droit_socle_acces"                             , "parent,eleve" ),
( "droit_socle_pourcentage_acquis"                , "parent,eleve" ),
( "droit_socle_etat_validation"                   , "" ),
( "droit_bulletin_appreciation_generale"          , "directeur,profprincipal" ),
( "droit_bulletin_impression_pdf"                 , "directeur,aucunprof" ),
( "duree_inactivite"                              , "30" ),
( "calcul_valeur_RR"                              , "0" ),
( "calcul_valeur_R"                               , "33" ),
( "calcul_valeur_V"                               , "67" ),
( "calcul_valeur_VV"                              , "100" ),
( "calcul_seuil_R"                                , "40" ),
( "calcul_seuil_V"                                , "60" ),
( "calcul_methode"                                , "geometrique" ),
( "calcul_limite"                                 , "5" ),
( "cas_serveur_host"                              , "" ),
( "cas_serveur_port"                              , "" ),
( "cas_serveur_root"                              , "" ),
( "css_background-color_NA"                       , "#ff9999" ),
( "css_background-color_VA"                       , "#ffdd33" ),
( "css_background-color_A"                        , "#99ff99" ),
( "gepi_url"                                      , "" ),
( "gepi_rne"                                      , "" ),
( "gepi_certificat_empreinte"                     , "" ),
( "note_image_style"                              , "Lomer" ),
( "note_texte_RR"                                 , "RR" ),
( "note_texte_R"                                  , "R" ),
( "note_texte_V"                                  , "V" ),
( "note_texte_VV"                                 , "VV" ),
( "note_legende_RR"                               , "Très insuffisant." ),
( "note_legende_R"                                , "Insuffisant." ),
( "note_legende_V"                                , "Satisfaisant." ),
( "note_legende_VV"                               , "Très satisfaisant." ),
( "acquis_texte_NA"                               , "NA" ),
( "acquis_texte_VA"                               , "VA" ),
( "acquis_texte_A"                                , "A" ),
( "acquis_legende_NA"                             , "Non acquis." ),
( "acquis_legende_VA"                             , "Partiellement acquis." ),
( "acquis_legende_A"                              , "Acquis." ),
( "enveloppe_horizontal_gauche"                   , "110" ),
( "enveloppe_horizontal_milieu"                   , "100" ),
( "enveloppe_horizontal_droite"                   , "20" ),
( "enveloppe_vertical_haut"                       , "50" ),
( "enveloppe_vertical_milieu"                     , "45" ),
( "enveloppe_vertical_bas"                        , "20" ),
( "bulletin_infos_etablissement"                  , "adresse,telephone,fax,courriel" ),
( "bulletin_infos_responsables"                   , "non" ),
( "bulletin_nombre_exemplaires"                   , "un" ),
( "bulletin_marge_gauche"                         , "5" ),
( "bulletin_marge_droite"                         , "5" ),
( "bulletin_marge_haut"                           , "5" ),
( "bulletin_marge_bas"                            , "10" ),
( "bulletin_modele_defaut"                        , "item_synthese" ),
( "bulletin_item_appreciation_matiere_presence"   , "1" ),
( "bulletin_item_appreciation_matiere_longueur"   , "150" ),
( "bulletin_item_appreciation_generale_presence"  , "1" ),
( "bulletin_item_pourcentage_acquis_presence"     , "0" ),
( "bulletin_item_pourcentage_acquis_modifiable"   , "1" ),
( "bulletin_item_pourcentage_acquis_classe"       , "0" ),
( "bulletin_item_note_moyenne_score_presence"     , "1" ),
( "bulletin_item_note_moyenne_score_modifiable"   , "1" ),
( "bulletin_item_note_moyenne_score_classe"       , "1" ),
( "bulletin_socle_pourcentage_acquis_presence"    , "1" ),
( "bulletin_socle_etat_validation_presence"       , "0" ),
( "bulletin_socle_appreciation_generale_presence" , "1" );

ALTER TABLE sacoche_parametre ENABLE KEYS;
