DROP TABLE IF EXISTS sacoche_socle_section;

CREATE TABLE sacoche_socle_section (
	section_id    SMALLINT(5)  UNSIGNED                NOT NULL AUTO_INCREMENT,
	pilier_id     TINYINT(3)   UNSIGNED                NOT NULL DEFAULT 0,
	section_ordre TINYINT(3)   UNSIGNED                NOT NULL DEFAULT 1 COMMENT "Commence à 1.",
	section_nom   VARCHAR(165) COLLATE utf8_unicode_ci NOT NULL DEFAULT "",
	PRIMARY KEY (section_id),
	KEY pilier_id (pilier_id)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE sacoche_socle_section DISABLE KEYS;

INSERT INTO sacoche_socle_section VALUES 
(  1,  1, 1, "Dire"),
(  2,  1, 2, "Lire"),
(  3,  1, 3, "Écrire"),
(  4,  1, 4, "Étude de la langue - vocabulaire"),
(  5,  1, 5, "Étude de la langue - grammaire"),
(  6,  1, 6, "Étude de la langue - orthographe"),
(  7,  2, 1, "Nombres et calcul"),
(  8,  2, 2, "Géométrie"),
(  9,  2, 3, "Grandeurs et mesures"),
( 10,  2, 4, "Organisation et gestion de données"),
( 11,  3, 1, "Connaître les principes et fondements de la vie civique et sociale"),
( 12,  3, 2, "Avoir un comportement responsable"),
( 13,  4, 1, "Dire"),
( 14,  4, 2, "Lire"),
( 15,  4, 3, "Écrire"),
( 16,  4, 4, "Étude de la langue - vocabulaire"),
( 17,  4, 5, "Étude de la langue - grammaire"),
( 18,  4, 6, "Étude de la langue - orthographe"),
( 19,  5, 1, "Réagir et dialoguer"),
( 20,  5, 2, "Comprendre à l’oral"),
( 21,  5, 3, "Parler en continu"),
( 22,  5, 4, "Lire"),
( 23,  5, 5, "Écrire"),
( 24,  6, 1, "Nombres et calcul"),
( 25,  6, 2, "Géométrie"),
( 26,  6, 3, "Grandeurs et mesures"),
( 27,  6, 4, "Organisation et gestion de données"),
( 28,  7, 1, "Pratiquer une démarche scientifique ou technologique"),
( 29,  7, 2, "Maîtriser des connaissances dans divers domaines scientifiques et les mobiliser dans des contextes scientifiques différents et dans des activités de la vie courante"),
( 30,  7, 3, "Environnement et développement durable"),
( 31,  8, 1, "S’approprier un environnement informatique de travail"),
( 32,  8, 2, "Adopter une attitude responsable"),
( 33,  8, 3, "Créer, produire, traiter, exploiter des données"),
( 34,  8, 4, "S’informer, se documenter"),
( 35,  8, 5, "Communiquer, échanger"),
( 36,  9, 1, "Avoir des repères relevant du temps et de l’espace"),
( 37,  9, 2, "Avoir des repères littéraires"),
( 73,  9, 3, "Lire et pratiquer différents langages"),
( 38,  9, 4, "Pratiquer les arts et avoir des repères en histoire des arts"),
( 39, 10, 1, "Connaître les principes et fondements de la vie civique et sociale"),
( 40, 10, 2, "Avoir un comportement responsable"),
( 41, 11, 1, "S’appuyer sur des méthodes de travail pour être autonome"),
( 42, 11, 2, "Faire preuve d’initiative"),
( 43, 11, 3, "Avoir une bonne maîtrise de son corps et une pratique physique (sportive ou artistique)"),
( 44, 12, 1, "Lire"),
( 45, 12, 2, "Écrire"),
( 46, 12, 3, "Dire"),
( 48, 13, 1, "Réagir et dialoguer"),
( 49, 13, 2, "Écouter et comprendre"),
( 50, 13, 3, "Parler en continu"),
( 51, 13, 4, "Lire"),
( 52, 13, 5, "Écrire"),
( 53, 14, 1, "Pratiquer une démarche scientifique et technologique, résoudre des problèmes"),
( 54, 14, 2, "Savoir utiliser des connaissances et des compétences mathématiques"),
( 55, 14, 3, "Savoir utiliser des connaissances dans divers domaines scientifiques"),
( 56, 14, 4, "Environnement et développement durable"),
( 57, 15, 1, "S’approprier un environnement informatique de travail"),
( 58, 15, 2, "Adopter une attitude responsable"),
( 59, 15, 3, "Créer, produire, traiter, exploiter des données"),
( 60, 15, 4, "S’informer, se documenter"),
( 61, 15, 5, "Communiquer, échanger"),
( 62, 16, 1, "Avoir des connaissances et des repères"),
( 67, 16, 2, "Situer dans le temps, l’espace, les civilisations"),
( 66, 16, 3, "Lire et pratiquer différents langages"),
( 74, 16, 4, "Faire preuve de sensibilité, d’esprit critique, de curiosité"),
( 68, 17, 1, "Connaître les principes et fondements de la vie civique et sociale"),
( 69, 17, 2, "Avoir un comportement responsable"),
( 70, 18, 1, "Être acteur de son parcours de formation et d’orientation"),
( 71, 18, 2, "Être capable de mobiliser ses ressources intellectuelles et physiques dans diverses situations"),
( 72, 18, 3, "Faire preuve d’initiative");

ALTER TABLE sacoche_socle_section ENABLE KEYS;
