#!/bin/bash
#
#### Variable a positionner en fonction du plugin
NAMEPLUGIN="Bcdiweb"
####
#
# Configuration Apache
rm -f  /etc/apache2/lcs-main/78_bcdi.conf

rm -r /home/BcdiPlug

# Suppression du menu administration BcdiWeb
#rm /var/www/lcs/includes/menu.d/96bcdiweb.inc

# Configuration de l copie automatique de la base
rm /etc/cron.d/bcdiweb  

# rechargement config apache
/etc/init.d/apache2 reload > /dev/null 2>&1

