#!/bin/bash
#
#### Variable a positionner en fonction du module
NAMEPLUGIN="Bcdiweb"
####
#
PATH2PLUGIN="/usr/share/lcs/Plugins/$NAMEPLUGIN"
echo "Script d'installation du module Bcdiweb";

# Creation de Data dans /home pour question de place
mkdir -p /home/BcdiPlug/Data
chown -R www-data /home/BcdiPlug 

# Configuration Apache
cp -a /usr/share/lcs/Plugins/Bcdiweb/progweb/confhttp/bcdiweb.conf  /etc/apache2/lcs-main/78_bcdi.conf


# Configuration de la copie automatique de la base
echo "PATH=/usr/bin" > /etc/cron.d/bcdiweb
echo '# m h dom mon dow user	command' >> /etc/cron.d/bcdiweb
echo "0 20 * * 0-5 www-data  /usr/share/lcs/Plugins/Bcdiweb/scripts/syncbcdi.sh" >> /etc/cron.d/bcdiweb  

# rechargement config apache
/etc/init.d/apache2 reload > /dev/null 2>&1

