#! /bin/sh
# postrm script for LCS  gedowl

set -e
case "$1" in
	purge|remove)
	# Update sudoers
        /usr/sbin/lcs-make-sudoers
        ;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

#DEBHELPER#

exit 0
