#! /bin/sh
# postrm script for LCS ent

set -e
case "$1" in
	purge|remove)
		# Remove params ENT
		mysql -e "DROP TABLE lcs_db.ent-lcs;" > /dev/null 2>&1
		mysql -e "DELETE FROM lcs_db.params WHERE params.cat = 6;" > /dev/null 2>&1
        ;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

#DEBHELPER#

exit 0
