#! /bin/sh
# postrm script for LCS apache2ssl

set -e
MODULE="apache2ssl"
APACHE2CONF="/etc/apache2/lcs-main/01_redirect.conf"

case "$1" in
	purge|remove)
        #
        # Désincription du module
        #
        mysql -e "DELETE FROM lcs_db.applis WHERE name = '$MODULE';" > /dev/null 2>&1
        #
        # Désactivation menu Certificat Apache SSL
        #
        if [ `grep '\"/Admin/apachecert.php",\"lcs_is_admin\",' /tmp/50services.inc | wc -l` = "1" ]; then
          sed -i "s/.*apachecert.php.*/#\t\t\"Certificat Apache SSL\",\"\/Admin\/listesdiff.php\",\"lcs_is_admin\",/" /var/www/lcs/includes/menu.d/50services.inc
        else
            sed -i "s/.*apachecert.php.*/#\t\t\"Certificat Apache SSL\",\"\/Admin\/listesdiff.php\",\"lcs_is_admin\"/" /var/www/lcs/includes/menu.d/50services.inc
        fi
        #
        # Remove redirect rule
        #
        rm -f $APACHE2CONF
        #
        # Désactivation mod ssl
        #
        a2dismod  ssl
        #
        # Disable lcs-ssl
        #
        a2dissite lcs-ssl
        #
        # Désactivation Listen
        #
         sed -i "/Listen 443/d" /etc/apache2/ports.conf
        #
        # Desactivation sudoers APACHESSLCERT
        #
        if [ `grep 'SECTION_APACHE2SSL' /etc/sudoers | wc -l` = "0" ]; then
          section_mgr --remove apache2ssl /etc/sudoers
        fi
        #
        # Effacement des certificats
        #
        rm -Rf /etc/apache2/ssl/server.*
        #
        # Apache2 differed restarting for web interface install module
        #
        if which at >/dev/null; then
          echo "Rechargement configuration Apache2 dans 1mn"
          at now+1minutes <<END
/etc/init.d/apache2 restart
sleep 2
END
        fi

        ;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

#DEBHELPER#

exit 0
