#! /bin/sh
# postinst script for LCS apache2ssl
set -e

# lecture d'un parametre lcs dans lcs_db.params

function get_lcsdb_params() {
  PARAMS=`echo  "SELECT value FROM params WHERE name='$1'"| mysql lcs_db -N`
  echo "$PARAMS"
}

case "$1" in
	install|configure)

    	;;

    	abort-upgrade|abort-remove|abort-deconfigure)
    	;;

    	*)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    	;;
esac

#DEBHELPER#

exit 0
