#! /bin/sh
# postrm script for LCS imap-ssl

set -e
MODULE="imap-ssl"

case "$1" in
	purge|remove)
        #
        # Désincription du module
        #
        mysql -e "DELETE FROM lcs_db.applis WHERE name = '$MODULE';" > /dev/null 2>&1
        #
;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

#DEBHELPER#

exit 0
