Document: lcs-openssh
Title: Debian lcs-openssh Manual
Author: <insert document author here>
Abstract: This manual describes what lcs-openssh is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lcs-openssh/lcs-openssh.sgml.gz

Format: postscript
Files: /usr/share/doc/lcs-openssh/lcs-openssh.ps.gz

Format: text
Files: /usr/share/doc/lcs-openssh/lcs-openssh.text.gz

Format: HTML
Index: /usr/share/doc/lcs-openssh/html/index.html
Files: /usr/share/doc/lcs-openssh/html/*.html

  
