#! /bin/sh
# postrm script for LCS CERT MANAGER

MODULE="certmanager"

set -e
case "$1" in
	purge|remove)
        #
        # unsubscribe module certmanager
        #
        mysql -e "DELETE FROM lcs_db.applis WHERE name = '$MODULE';" > /dev/null 2>&1		             
        ;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

#DEBHELPER#

exit 0
