#! /bin/sh
# postinst script for LCS CERT MANAGER
set -e


MODULE="certmanager"


# lecture d'un parametre lcs dans lcs_db.params

get_lcsdb_params() {
  PARAMS=`echo  "SELECT value FROM params WHERE name='$1'"| mysql lcs_db -N`
  echo "$PARAMS"
}

case "$1" in
	install|configure)
            #
            # registration module type S in applis.lcs_db
            #
            CERTMGR=`/usr/bin/mysql -e "SELECT id from lcs_db.applis WHERE name='certmanager';"`
            VER=$(dpkg-query -f '${Version}' -W lcs-certmanager)
            if [ -z "$APACHE2SSL" ]; then
                /usr/bin/mysql -e "INSERT INTO lcs_db.applis (id, name, value, descr, num_maj, version, chemin, type) VALUES ('', '$MODULE', '1', 'Gestion des certificats SSL', '$INDICEMAJNBR', '$VER', '$PATHMOD', 'S');"
            else
               /usr/bin/mysql -e "UPDATE lcs_db.applis SET version='$VER' WHERE name='$MODULE';" 
            fi
            #
            # Generate certificat
            #
            FQN=`hostname -f`            
            if [ ! -e /etc/ssl/lcs/$FQN.crt -o ! -e /etc/ssl/lcs/$FQN.key ]; then
              echo "Generation certificat SSL"
              FQN=`hostname -f`
              DOMAIN=$(get_lcsdb_params domain)
              COUNTRYNAME=$(get_lcsdb_params country)
              PROVINCENAME=$(get_lcsdb_params province)
              LOCALITYNAME=$(get_lcsdb_params locality)
              ORGANIZATIONNAME=$(get_lcsdb_params organization)
              ORGANIZATIONALUNITNAME=$(get_lcsdb_params organizationalunit)
              # apache2-ssl-cert.sh <FQN> <DOMAIN> <COUNTRYNAME> <PROVINCENAME> <LOCALITYNAME> <ORGANIZATIONNAME> <ORGANIZATIONALUNITNAME>
              /usr/sbin/lcs-certssl-gen $FQN $DOMAIN $COUNTRYNAME $PROVINCENAME $LOCALITYNAME $ORGANIZATIONNAME $ORGANIZATIONALUNITNAME
            else
            	echo "move existing certificat"
            	mv /etc/apache2/ssl/* /etc/ssl/lcs
            	rename /etc/ssl/lcs/server.crt /etc/ssl/lcs/$FQN.crt
            	rename /etc/ssl/lcs/server.key /etc/ssl/lcs/$FQN.key
            fi
            #
            # Add sudoers section
            #
				/usr/sbin/lcs-make-sudoers
            #
            #  Apache2 differed restarting for web interface install module
            #
          echo "Rechargement configuration Apache2 dans 1mn"
          at now+1minutes <<END
/etc/init.d/apache2 restart
sleep 2
END
    	;;

    	abort-upgrade|abort-remove|abort-deconfigure)
    	;;

    	*)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    	;;
esac

#DEBHELPER#

exit 0