#! /bin/sh
# postinst script for LCS CERT MANAGER
set -e

MODULE="certmanager"

# lecture d'un parametre lcs dans lcs_db.params

get_lcsdb_params() {
  PARAMS=`echo  "SELECT value FROM params WHERE name='$1'"| mysql lcs_db -N`
  echo "$PARAMS"
}

case "$1" in
	install|configure)
            #
            # registration module type S in applis.lcs_db
            #
            CERTMGR=`/usr/bin/mysql -e "SELECT id from lcs_db.applis WHERE name='$MODULE';"`
            VER=$(dpkg-query -f '${Version}' -W lcs-certmanager)
            CERTMGR=`/usr/bin/mysql -e "SELECT id from lcs_db.applis WHERE name='$MODULE';"`
            if [ -z "$CERTMGR" ]; then
                /usr/bin/mysql -e "INSERT INTO lcs_db.applis (id, name, value, descr, num_maj, version, chemin, type) VALUES ('', '$MODULE', '1', 'Gestion des certificats SSL', '$INDICEMAJNBR', '$VER', '$PATHMOD', 'S');"
            else
               /usr/bin/mysql -e "UPDATE lcs_db.applis SET version='$VER' WHERE name='$MODULE';" 
            fi
            #
            # Add table sslcert in lcs_db
            #
            mysql lcs_db < /var/lib/lcs/certmanager/Sql/sslcert.sql
            #
            # Generate certificat
            #
				/usr/sbin/lcs-certmanager -c
				#
				# Select autosigned certificat
				#
				SSLCERTNAME=`hostname -f`_as
				/usr/sbin/lcs-certmanager -s $SSLCERTNAME
            #
            # Add sudoers section
            #
				/usr/sbin/lcs-make-sudoers
				#
				# fix rights on certmanager
				#
				chown root:www-data /usr/share/lcs/certmanager
				chmod 770 /usr/share/lcs/certmanager
    	;;

    	abort-upgrade|abort-remove|abort-deconfigure)
    	;;

    	*)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    	;;
esac

#DEBHELPER#

exit 0