#! /bin/bash
# preinst script for lcs-pma

set -e
case "$1" in
install)
	#Suppression des fichiers de la version précédente
	rm -rf /usr/share/lcs/pma
;;
abort-upgrade)
;;
upgrade)
;;
*)
echo "preinst called with unknown argument \`$1'" >&2
exit 1
;;
esac
exit 0



