#! /bin/sh
set -e

MODULE="spip"
APACHECONF="/etc/lcs/apache.conf"
APACHE2CONF="/etc/apache2/lcs-main/75_spip.conf"

case "$1" in
    purge|remove)
        #
        # Suppression de l'alias 
        #
        # cas de l'ancienne conf apache
        if [ -e $APACHECONF ]; then
          grep -v 'Alias /$MODULE/ /usr/share/lcs/$MODULE/' $APACHECONF > /tmp/apache.conf
          mv /tmp/apache.conf $APACHECONF
          if [ -e /etc/init.d/apache ]; then
            /etc/init.d/apache reload > /dev/null 2>&1
          fi
        fi
        # cas de la nouvelle configuration apache
        if [ -e $APACHE2CONF ]; then
          rm -f $APACHE2CONF
          /etc/init.d/apache2 reload > /dev/null 2>&1
        fi


        #
        # Suppression de la base de données spip_lcs
        #
        mysql -e "DROP DATABASE IF EXISTS spip_lcs;" > /dev/null 2>&1
        #
        # Supression des entrées dans mysql db
        #
        mysql -e "DELETE FROM mysql.db WHERE Db = 'spip_lcs';"; > /dev/null 2>&1
        #
        # Suppression de l'utilisateur spip.manager
        #
        /usr/share/lcs/sbin/userDel.pl spip.manager > /dev/null 2>&1
        #
        # Desinscription du module de la table lcs_db.applis
        #
        mysql -e "DELETE FROM lcs_db.applis WHERE name = '$MODULE';"; > /dev/null 2>&1
        #
        # Nettoyage des repertoires
        # 
        if [ -e /usr/share/lcs/$MODULE ]; then
	   rm -R /usr/share/lcs/$MODULE
        fi
        if [ -e /var/lib/lcs/$MODULE ]; then
	   rm -R /var/lib/lcs/$MODULE
        fi
        exit 0
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

exit 0
