dev:
  doctrine:
    class:    sfDoctrineDatabase
    param:
      dsn:    mysql://mysql_cas:wawa@localhost/CAS
prod:
  doctrine:
    class:    sfDoctrineDatabase
    param:
      dsn:    mysql://mysql_cas:wawa@localhost/CAS
