#!/bin/bash
#
#### Variable a positionner en fonction du plugin
NAMEPLUGIN="Cdt"
####
#
PATH2PLUGIN="/usr/share/lcs/Plugins/$NAMEPLUGIN"
echo "Script d'installation du plugin Cahier de textes";
#
# Nettoyage
#
rm $PATH2PLUGIN/Admin/install_mysql.sql
mv $PATH2PLUGIN/Admin/install_mysql.sq $PATH2PLUGIN/Admin/install_mysql.sql
